/**
 * Mission facts: the key numbers every mission builder reports in MissionTimeline.facts, for the
 * lesson content, the cards, ACCURACY.md, the report printer (scripts/mission-report.mjs) and
 * the tests. The keys are STABLE: the content tests read them. Add new keys here; never rename
 * or drop one without telling the content owner. A test checks that each mission reports
 * exactly the keys listed for it below.
 *
 * Conventions: times ('.t', and '.t' inside a name) are mission seconds from liftoff (T-0,
 * negative before); altitudes are above the spherical Earth (6,371 km) or, for the lunar
 * closest approach, the Moon (1,737.4 km); 'g' is the sensed (non-gravitational) acceleration
 * in units of 9.80665 m/s^2; velocity changes are the burn's rocket-equation delta-v unless
 * stated. 'internal' keys are converged search values kept as warm starts (not for lessons).
 */
import type { MissionId } from '../types';

export interface FactDoc {
  unit: string;
  /** Missions that report this key. */
  missions: MissionId[];
  about: string;
}

export const FACTS: Record<string, FactDoc> = {
  'liftoffMass': { unit: 'kg', missions: ['leo', 'suborbital', 'gto', 'station', 'lunar'], about: 'stack mass at liftoff (T-0)' },
  'liftoffTW': { unit: 'ratio', missions: ['leo', 'gto', 'station', 'lunar'], about: 'liftoff thrust-to-weight: 7 x E-1 sea-level rated thrust / liftoff weight' },
  'kickDeg': { unit: 'deg', missions: ['leo', 'suborbital', 'gto', 'station', 'lunar'], about: 'pitch-kick angle after tower clearance (suborbital: the tilt off the vertical)' },
  'towerClear': { unit: 's', missions: ['leo', 'gto', 'station', 'lunar'], about: 'time the stack clears the tower' },
  'maxQ.t': { unit: 's', missions: ['leo', 'gto', 'station', 'lunar'], about: 'time of maximum dynamic pressure' },
  'maxQ.kPa': { unit: 'kPa', missions: ['leo', 'gto', 'station', 'lunar'], about: 'maximum dynamic pressure' },
  'maxQ.altKm': { unit: 'km', missions: ['leo', 'gto', 'station', 'lunar'], about: 'altitude at maximum dynamic pressure' },
  'maxQ.mach': { unit: 'Mach', missions: ['leo', 'gto', 'station', 'lunar'], about: 'Mach number at maximum dynamic pressure' },
  'meco.t': { unit: 's', missions: ['leo', 'suborbital', 'gto', 'station', 'lunar'], about: 'first-stage main engine cutoff' },
  'meco.altKm': { unit: 'km', missions: ['leo', 'suborbital', 'gto', 'station', 'lunar'], about: 'altitude at the end of the 0.8 s MECO shutdown transient (the stack climbs about 1 km more after the MECO event on orbital flights)' },
  'meco.speed': { unit: 'm/s', missions: ['leo', 'suborbital', 'gto', 'station', 'lunar'], about: 'inertial speed at the end of the MECO shutdown transient' },
  'meco.airSpeed': { unit: 'm/s', missions: ['leo', 'gto', 'station', 'lunar'], about: 'speed relative to the rotating air at the end of the MECO shutdown transient' },
  'meco.gammaDeg': { unit: 'deg', missions: ['leo', 'suborbital', 'gto', 'station', 'lunar'], about: 'air-relative flight-path angle above the horizontal at the end of the MECO shutdown transient' },
  'meco.downrangeKm': { unit: 'km', missions: ['leo', 'gto', 'station', 'lunar'], about: 'ground distance from the pad at the end of the MECO shutdown transient' },
  'meco.s1PropLeft': { unit: 'kg', missions: ['leo', 'suborbital', 'gto', 'station', 'lunar'], about: 'first-stage propellant left after the MECO shutdown transient (the landing reserve on recovery flights)' },
  'stageSep.t': { unit: 's', missions: ['leo', 'gto', 'station', 'lunar'], about: 'stage separation' },
  'ses1.t': { unit: 's', missions: ['leo', 'gto', 'station', 'lunar'], about: 'upper-stage engine start' },
  'fairingSep.t': { unit: 's', missions: ['leo', 'gto', 'lunar'], about: 'payload fairing separation command (the halves release 1.2 s later)' },
  'payloadKg': { unit: 'kg', missions: ['leo', 'suborbital', 'gto', 'lunar'], about: 'payload mass flown' },
  'payloadSep.t': { unit: 's', missions: ['leo', 'gto', 'lunar'], about: 'payload separation from the upper stage' },
  'boosterImpact.t': { unit: 's', missions: ['gto', 'station', 'lunar'], about: 'expended booster reaches the sea (tracked to the surface; illustrative, a real expended stage breaks up during entry)' },
  'boosterImpact.downrangeKm': { unit: 'km', missions: ['gto', 'station', 'lunar'], about: 'ground distance from the pad to where the expended booster falls into the ocean' },
  'rtls.reserveKg': { unit: 'kg', missions: ['leo'], about: 'first-stage propellant reserved for the return at MECO' },
  'rtls.reservePct': { unit: '%', missions: ['leo'], about: 'that reserve as a share of the full first-stage load' },
  'rtls.boostbackDv': { unit: 'm/s', missions: ['leo'], about: 'velocity change of the boostback burn' },
  'rtls.entryDv': { unit: 'm/s', missions: ['leo'], about: 'velocity change of the entry burn' },
  'rtls.landingDv': { unit: 'm/s', missions: ['leo', 'suborbital'], about: 'velocity change of the landing burn' },
  'rtls.apogeeKm': { unit: 'km', missions: ['leo', 'suborbital'], about: 'booster apogee after separation' },
  'rtls.touchdown.t': { unit: 's', missions: ['leo', 'suborbital'], about: 'booster touchdown on the landing zone' },
  'rtls.landingErrorM': { unit: 'm', missions: ['leo', 'suborbital'], about: 'touchdown distance from the landing-zone centre' },
  'rtls.touchdownSpeed': { unit: 'm/s', missions: ['leo', 'suborbital'], about: 'booster speed at touchdown' },
  'rtls.propLeftKg': { unit: 'kg', missions: ['leo', 'suborbital'], about: 'booster propellant left after touchdown' },
  'rtls.tiltDeg': { unit: 'deg', missions: ['leo', 'suborbital'], about: 'booster axis tilt from the local vertical at touchdown' },
  'rtls.maxDecelG': { unit: 'g', missions: ['leo', 'suborbital'], about: 'peak sensed deceleration of the returning booster while unpowered (air drag between the burns); during the landing burn thrust adds to the drag and telemetry reads more' },
  'rtls.maxQkPa': { unit: 'kPa', missions: ['leo'], about: 'peak dynamic pressure on the returning booster' },
  'insertion.periKm': { unit: 'km', missions: ['leo', 'station'], about: 'perigee altitude of the insertion orbit at SECO' },
  'insertion.apoKm': { unit: 'km', missions: ['leo', 'station'], about: 'apogee altitude of the insertion orbit at SECO' },
  'insertion.incDeg': { unit: 'deg', missions: ['station'], about: 'inclination of the insertion orbit to the equator' },
  'seco.t': { unit: 's', missions: ['leo', 'station'], about: 'upper-stage engine cutoff (SECO) into the insertion orbit' },
  'seco.s2PropLeftKg': { unit: 'kg', missions: ['leo', 'station'], about: 'upper-stage propellant left at SECO' },
  'circ.t': { unit: 's', missions: ['leo'], about: 'start of the circularization burn at the insertion apogee' },
  'circ.dv': { unit: 'm/s', missions: ['leo'], about: 'velocity change of the circularization burn' },
  'orbit.periKm': { unit: 'km', missions: ['leo'], about: 'final orbit perigee altitude' },
  'orbit.apoKm': { unit: 'km', missions: ['leo'], about: 'final orbit apogee altitude' },
  'orbit.incDeg': { unit: 'deg', missions: ['leo'], about: 'final orbit inclination' },
  'orbit.s2PropLeftKg': { unit: 'kg', missions: ['leo'], about: 'upper-stage propellant left after circularization' },
  'orbit.periodMin': { unit: 'min', missions: ['leo'], about: 'final orbit period' },
  's1LoadKg': { unit: 'kg', missions: ['suborbital'], about: 'first-stage propellant loaded (partial load, computed)' },
  's1LoadPct': { unit: '%', missions: ['suborbital'], about: 'that load as a share of the full first-stage load' },
  'launchAzimuthDeg': { unit: 'deg', missions: ['suborbital'], about: 'launch direction, clockwise from north' },
  'capsuleSep.t': { unit: 's', missions: ['suborbital', 'station'], about: 'capsule separation (suborbital: from the booster; station: from the upper stage)' },
  'apogee.t': { unit: 's', missions: ['suborbital', 'gto'], about: 'time of apogee (suborbital capsule; GTO satellite on the transfer orbit)' },
  'apogee.km': { unit: 'km', missions: ['suborbital'], about: 'capsule apogee altitude' },
  'karman.freeFallS': { unit: 's', missions: ['suborbital'], about: 'time the capsule spends above 100 km' },
  'entry.peakG': { unit: 'g', missions: ['suborbital', 'return'], about: 'peak sensed deceleration of the capsule during entry' },
  'entry.peakG.t': { unit: 's', missions: ['suborbital', 'return'], about: 'time of the peak deceleration' },
  'entry.peakG.altKm': { unit: 'km', missions: ['return'], about: 'altitude of the peak deceleration' },
  'entry.peakHeating.t': { unit: 's', missions: ['suborbital', 'return'], about: 'time of peak convective heating (stagnation point)' },
  'entry.peakHeating.altKm': { unit: 'km', missions: ['suborbital', 'return'], about: 'altitude of peak heating' },
  'entry.peakHeating.kWm2': { unit: 'kW/m^2', missions: ['suborbital', 'return'], about: 'peak stagnation-point heating rate (Sutton-Graves)' },
  'entry.peakHeating.speed': { unit: 'm/s', missions: ['return'], about: 'air-relative speed at peak heating' },
  'entry.maxQkPa': { unit: 'kPa', missions: ['suborbital'], about: 'peak dynamic pressure on the capsule' },
  'entry.heatLoadMJm2': { unit: 'MJ/m^2', missions: ['return'], about: 'integrated stagnation-point heat load' },
  'entry.blackoutS': { unit: 's', missions: ['return'], about: 'duration of the high-heating band (heating above a quarter of its peak; plasma blackout)' },
  'drogue.t': { unit: 's', missions: ['suborbital', 'return'], about: 'drogue parachute deployment' },
  'main.t': { unit: 's', missions: ['suborbital', 'return'], about: 'main parachute deployment (reefed)' },
  'splash.t': { unit: 's', missions: ['suborbital', 'return'], about: 'splashdown' },
  'splash.speed': { unit: 'm/s', missions: ['suborbital', 'return'], about: 'capsule speed at splashdown (under the three mains)' },
  'splash.eastKm': { unit: 'km', missions: ['suborbital'], about: 'splashdown east of the pad' },
  'splash.northKm': { unit: 'km', missions: ['suborbital'], about: 'splashdown north of the pad' },
  'parking.periKm': { unit: 'km', missions: ['gto', 'lunar'], about: 'parking orbit perigee altitude' },
  'parking.apoKm': { unit: 'km', missions: ['gto', 'lunar'], about: 'parking orbit apogee altitude' },
  'parking.incDeg': { unit: 'deg', missions: ['gto', 'lunar'], about: 'parking orbit inclination' },
  'seco1.t': { unit: 's', missions: ['gto', 'lunar'], about: 'first upper-stage cutoff, into the parking orbit' },
  'seco1.s2PropLeftKg': { unit: 'kg', missions: ['gto', 'lunar'], about: 'upper-stage propellant left at SECO-1' },
  'node.t': { unit: 's', missions: ['gto'], about: 'descending-node (equator) crossing where the GTO injection is centred' },
  'ses2.t': { unit: 's', missions: ['gto'], about: 'upper-stage restart for the GTO injection' },
  'seco2.t': { unit: 's', missions: ['gto'], about: 'second upper-stage cutoff: transfer orbit reached' },
  'injection.burnS': { unit: 's', missions: ['gto'], about: 'duration of the GTO injection burn' },
  'injection.dvIdeal': { unit: 'm/s', missions: ['gto'], about: 'ideal (rocket-equation) velocity change of the GTO injection burn' },
  'gto.periKm': { unit: 'km', missions: ['gto'], about: 'transfer orbit perigee altitude' },
  'gto.apoKm': { unit: 'km', missions: ['gto'], about: 'transfer orbit apogee altitude (target 35,786 km)' },
  'gto.periodH': { unit: 'h', missions: ['gto'], about: 'transfer orbit period' },
  'seco2.s2PropLeftKg': { unit: 'kg', missions: ['gto'], about: 'upper-stage propellant left at SECO-2' },
  'apogee.climbH': { unit: 'h', missions: ['gto'], about: 'time from satellite separation to apogee' },
  'apogeeBurn.dvToGainAtStart': { unit: 'm/s', missions: ['gto'], about: 'ideal impulsive step at apogee: circular speed minus apogee speed' },
  'apogeeBurn.t': { unit: 's', missions: ['gto'], about: 'start of the explanatory apogee-engine burn' },
  'apogeeBurn.durationH': { unit: 'h', missions: ['gto'], about: 'duration of that single long burn' },
  'apogeeBurn.dv': { unit: 'm/s', missions: ['gto'], about: 'velocity change it delivered (rocket equation); above the ideal step: finite-burn loss' },
  'apogeeBurn.propUsedKg': { unit: 'kg', missions: ['gto'], about: 'satellite propellant it used' },
  'final.periKm': { unit: 'km', missions: ['gto'], about: 'satellite orbit perigee altitude after the burn' },
  'final.apoKm': { unit: 'km', missions: ['gto'], about: 'satellite orbit apogee altitude after the burn' },
  'crew.capsuleKg': { unit: 'kg', missions: ['station'], about: 'crew capsule mass flown' },
  'crew.serviceModuleKg': { unit: 'kg', missions: ['station'], about: 'service module mass flown (dry + propellant)' },
  'crew.abortTowerKg': { unit: 'kg', missions: ['station'], about: 'abort tower mass flown' },
  'crew.dataset': { unit: '0/1', missions: ['station'], about: '1 when the dataset crew stack (spec.ts: capsule, service module, abort tower) is flown; the station mission expends its booster to carry it' },
  'les.t': { unit: 's', missions: ['station'], about: 'abort tower jettison' },
  'insertion.stationLeadDeg': { unit: 'deg', missions: ['station'], about: 'angle the station leads the capsule by at SECO' },
  'phasing.revs': { unit: 'count', missions: ['station'], about: 'phasing revolutions before the first raise burn' },
  'phasingBurn1.t': { unit: 's', missions: ['station'], about: 'first raise burn (at perigee)' },
  'phasingBurn1.dv': { unit: 'm/s', missions: ['station'], about: 'its velocity change' },
  'phasingBurn2.t': { unit: 's', missions: ['station'], about: 'second raise burn (at apogee)' },
  'phasingBurn2.dv': { unit: 'm/s', missions: ['station'], about: 'its velocity change' },
  'raise.periKm': { unit: 'km', missions: ['station'], about: 'capsule orbit perigee altitude after the raise burns' },
  'raise.apoKm': { unit: 'km', missions: ['station'], about: 'capsule orbit apogee altitude after the raise burns' },
  'approach.t': { unit: 's', missions: ['station'], about: 'start of the relative-motion (Clohessy-Wiltshire) approach' },
  'approach.behindKm': { unit: 'km', missions: ['station'], about: 'capsule distance behind the station then' },
  'approach.belowKm': { unit: 'km', missions: ['station'], about: 'capsule distance below the station then' },
  'cw.dv1': { unit: 'm/s', missions: ['station'], about: 'first impulse of the two-impulse transfer to the 400 m hold point' },
  'cw.dv2': { unit: 'm/s', missions: ['station'], about: 'second impulse (arrival at the hold point)' },
  'holdPoint.t': { unit: 's', missions: ['station'], about: 'arrival at the 400 m hold point below the station' },
  'softCapture.t': { unit: 's', missions: ['station'], about: 'soft capture (contact)' },
  'hardCapture.t': { unit: 's', missions: ['station'], about: 'hard capture (hooks closed)' },
  'docking.closingSpeed': { unit: 'm/s', missions: ['station'], about: 'closing speed at contact' },
  'docking.capsulePortY': { unit: 'm', missions: ['station'], about: 'capsule docking-port face, model frame y' },
  'docking.hoursAfterLaunch': { unit: 'h', missions: ['station'], about: 'time from liftoff to soft capture' },
  'sm.propLeftKg': { unit: 'kg', missions: ['station'], about: 'service-module propellant left after docking' },
  'station.altKm': { unit: 'km', missions: ['station'], about: 'station orbit altitude (circular)' },
  'station.periodMin': { unit: 'min', missions: ['station'], about: 'station orbit period' },
  'capsuleKg': { unit: 'kg', missions: ['return'], about: 'crew capsule mass (spec.ts CAPSULE)' },
  'serviceModuleKg': { unit: 'kg', missions: ['return'], about: 'service module mass at undocking (spec.ts SERVICE_MODULE)' },
  'undock.t': { unit: 's', missions: ['return'], about: 'undocking (mission time of the lesson clock)' },
  'departureDv': { unit: 'm/s', missions: ['return'], about: 'departure burn velocity change' },
  'deorbit.t': { unit: 's', missions: ['return'], about: 'deorbit burn start' },
  'deorbit.dv': { unit: 'm/s', missions: ['return'], about: 'deorbit burn velocity change (retrograde, service-module engine)' },
  'deorbit.burnS': { unit: 's', missions: ['return'], about: 'deorbit burn duration' },
  'deorbit.perigeeKm': { unit: 'km', missions: ['return'], about: 'perigee altitude after the deorbit burn' },
  'smSep.t': { unit: 's', missions: ['return'], about: 'service module separation' },
  'smSep.smPropLeftKg': { unit: 'kg', missions: ['return'], about: 'service-module propellant left at separation' },
  'entryInterface.t': { unit: 's', missions: ['return'], about: 'entry interface (120 km)' },
  'splash.lat': { unit: 'deg', missions: ['return'], about: 'splashdown latitude' },
  'splash.lon': { unit: 'deg', missions: ['return'], about: 'splashdown longitude (east positive)' },
  'splash.eastOfPadKm': { unit: 'km', missions: ['return'], about: 'splashdown distance east of the pad' },
  'entryToSplashS': { unit: 's', missions: ['return'], about: 'time from entry interface to splashdown' },
  'deorbitToSplashS': { unit: 's', missions: ['return'], about: 'time from the deorbit burn to splashdown' },
  'tli.t': { unit: 's', missions: ['lunar'], about: 'trans-lunar injection burn start' },
  'tli.burnS': { unit: 's', missions: ['lunar'], about: 'TLI burn duration' },
  'tli.speed': { unit: 'm/s', missions: ['lunar'], about: 'inertial speed at TLI cutoff' },
  'tli.c3km2s2': { unit: 'km^2/s^2', missions: ['lunar'], about: 'characteristic energy after TLI (negative: still bound to the Earth)' },
  'tli.s2PropLeftKg': { unit: 'kg', missions: ['lunar'], about: 'upper-stage propellant left after TLI' },
  'moonPhase0Deg': { unit: 'deg', missions: ['lunar'], about: 'Moon phase angle at T-0 chosen by the search (MissionTimeline.moonPhase0)' },
  'soiEnter.t': { unit: 's', missions: ['lunar'], about: 'entry into the Moon\'s sphere of influence' },
  'soiExit.t': { unit: 's', missions: ['lunar'], about: 'exit from the sphere of influence' },
  'soiKm': { unit: 'km', missions: ['lunar'], about: 'sphere-of-influence radius used' },
  'closestApproach.t': { unit: 's', missions: ['lunar'], about: 'closest approach to the Moon' },
  'closestApproach.altKm': { unit: 'km', missions: ['lunar'], about: 'altitude above the lunar surface at closest approach' },
  'closestApproach.farSide': { unit: '0/1', missions: ['lunar'], about: '1 when closest approach is on the far side (beyond the Moon from the Earth)' },
  'closestApproach.trailingSide': { unit: '0/1', missions: ['lunar'], about: '1 when it passes behind the Moon\'s orbital motion' },
  'closestApproach.angleFromEarthDeg': { unit: 'deg', missions: ['lunar'], about: 'angle between the Earth direction and the probe, seen from the Moon' },
  'closestApproach.speedRelMoon': { unit: 'm/s', missions: ['lunar'], about: 'speed relative to the Moon at closest approach' },
  'cruise.days': { unit: 'days', missions: ['lunar'], about: 'time from probe separation to closest approach' },
  'outbound.energy': { unit: 'J/kg', missions: ['lunar'], about: 'geocentric specific orbital energy after the flyby' },
  'outbound.ecc': { unit: 'ratio', missions: ['lunar'], about: 'geocentric eccentricity after the flyby' },
  'outbound.radialSpeed': { unit: 'm/s', missions: ['lunar'], about: 'geocentric radial speed at the end of the lesson' },
  'outbound.distanceKm': { unit: 'km', missions: ['lunar'], about: 'distance from the Earth at the end of the lesson' },
  'outbound.perigeeAltKm': { unit: 'km', missions: ['lunar'], about: 'perigee altitude of the two-body Earth orbit the probe is on after the flyby (negative: the path meets the Earth, a free return)' },
  'outbound.earthReturnDays': { unit: 'days', missions: ['lunar'], about: 'two-body estimate of the time from leaving the Moon\'s sphere of influence to reaching 120 km over the Earth, if uncorrected (0: it does not return)' },
  'search.kickDeg': { unit: 'deg', missions: ['leo', 'gto', 'station', 'lunar'], about: 'internal: converged pitch-kick search value' },
  'search.ltgA': { unit: '-', missions: ['leo', 'gto', 'station', 'lunar'], about: 'internal: converged linear-tangent steering coefficient A' },
  'search.ltgB': { unit: '1/s', missions: ['leo', 'gto', 'station', 'lunar'], about: 'internal: converged linear-tangent steering coefficient B' },
  'search.rtlsReserveKg': { unit: 'kg', missions: ['leo'], about: 'internal: converged RTLS reserve search value' },
  'search.rtlsBiasE': { unit: 'm', missions: ['leo'], about: 'internal: converged boostback aim bias, east' },
  'search.rtlsBiasN': { unit: 'm', missions: ['leo'], about: 'internal: converged boostback aim bias, north' },
  'search.theta0': { unit: 'rad', missions: ['return'], about: 'internal: station orbit phase angle at T-0 chosen by the return search' },
  'search.tU': { unit: 's', missions: ['return'], about: 'internal: undocking time chosen by the return search' },
};

/** The fact keys a mission reports (in the order listed above). */
export function factKeys(id: MissionId): string[] {
  return Object.keys(FACTS).filter((k) => FACTS[k].missions.includes(id));
}
