/**
 * Propellant and pressurization lessons: tanks, the LOX downcomer, helium pressurization, the
 * engine's main valves and the upper stage's settling thrusters.
 */
import type { PartLesson, PartNote } from '../types';
import { at, lesson, mats, note } from './util';
import { F } from './derived';

export const FLUIDS: (PartLesson | PartNote)[] = [
  lesson({
    id: 'main-valves',
    summary: 'The main LOX valve and main fuel valve on each engine: fast, leak-tight valves that start the engine in the right order and stop it cleanly.',
    where: 'On each E-1 between the turbopump discharges and the thrust chamber. Look for the two chunky valve bodies with actuators on the high-pressure lines: one on the LOX line to the dome above the injector, one on the fuel line to the coolant inlet manifold low on the nozzle.',
    connections: ['turbopump', 'injector', 'combustion-chamber', 'engine', 'igniter', 'avionics'],
    function: 'Open and close the main propellant flows on command, in a timed sequence, and hold tight against high pressure and cryogenic temperature when closed.',
    how: 'The valves are ball or butterfly types moved by actuators on command from the engine controller. In a typical start, oxygen leads slightly so the LOX dome and chamber fill with oxygen; the TEA-TEB slug arrives ahead of the fuel and ignites on contact, then the fuel flow builds and the turbopump comes up to speed. At shutdown the LOX valve closes first, so the chamber ends fuel-rich: hot oxygen-rich gas would attack the copper liner and injector. Throttle is set mainly through the gas generator (turbine power), not by partly closing the main valves.',
    why: 'A liquid engine\'s abilities to start on command, shut down precisely and restart all depend on these valves. A clean, repeatable cutoff also sets how exactly the stage reaches its target velocity.',
    phases: [
      at('leo', 'pad', 'Closed, while small bleed valves let LOX chill the pumps before start.'),
      at('leo', 'ignition', 'Open in sequence to start the seven engines.'),
      at('leo', 'meco', 'Close in sequence to shut the cluster down cleanly.'),
      at('leo', 'seco', 'The E-1V\'s valves close when guidance calls cutoff.'),
    ],
    environment: `LOX at ${F.loxBoil} and pump discharge pressures well above the ${F.e1Pc} chamber pressure; opening and closing in fractions of a second; vibration from the turbopump and the chamber.`,
    figures: [
      { label: 'Valves per engine', value: '2 main valves', note: 'Plus smaller valves for the gas generator, bleeds and purges' },
      { label: 'Flow through the LOX valve', value: F.e1Lox, note: 'Per engine at full thrust, computed' },
    ],
    materials: mats('main-valves'),
    materialsWhy: 'Valve bodies are stainless steel: strong, tough at LOX temperature and compatible with both propellants when oxygen-clean. Seats in hot-side valves are nickel superalloy, which keeps its shape and strength where gas-generator or warm fuel flows. Seals use materials qualified for oxygen service.',
    manufacturing: 'Bodies are forged or cast and precisely machined; balls, discs and seats are lapped for tightness; everything in the oxygen path is cleaned to strict particle and hydrocarbon limits before assembly.',
    inspection: 'Leak tests at cryogenic temperature, timing tests of opening and closing, and cycle tests. In flight, position sensors confirm every valve movement, and a valve that does not move as commanded stops the engine start.',
    misconception: '"Throttling is like closing a garden tap part way." In a gas-generator engine the throttle is set by how much power the turbine gets; the main valves are open or closed.',
    ifAbsent: 'Without the main valves the engine could not start in the right sequence, stop on command or restart. A failed engine could not be isolated from the others.',
    depth: {
      quick: 'Two big valves let oxygen and fuel into the engine at exactly the right moments. The order matters as much as the timing.',
      engineering: 'Start and shutdown transients are where engines are most often damaged. Oxygen lead at start, fuel-rich cutoff at shutdown, and precise timing limit pressure spikes and hot oxygen-rich conditions. Cutoff repeatability sets the uncertainty in the final velocity of each stage.',
      materials: 'Stainless steel for tough, oxygen-compatible bodies at cryogenic temperature; superalloy where seats see heat. Cleanliness for oxygen service is a manufacturing requirement in itself.',
    },
    demo: 'feed-flow',
    sources: ['huzel-huang-sp125', 'nasa-valves', 'sutton-rpe'],
  }),

  lesson({
    id: 's1-lox-tank',
    summary: `The booster's upper tank, holding ${F.s1Lox} of liquid oxygen at ${F.loxBoil}: most of the propellant mass, stored in a thin aluminium shell that is also the vehicle's structure.`,
    where: `The long upper section of the first stage, from ${F.st.s1LoxAftApex} to about ${F.st.s1LoxFwdApex} (${F.s1LoxTankLength} apex to apex), above the intertank and below the forward skirt. In the cutaway: the ellipsoidal domes, the orthogrid ribs inside the barrel, the anti-slosh baffle rings, the helium bottles (COPVs) on brackets near the top of the tank, and the downcomer leaving the aft dome.`,
    connections: ['lox-downcomer', 'pressurization', 's1-intertank', 'interstage', 'grid-fins', 'cold-gas-rcs', 'service-tower'],
    function: 'Store the oxidizer for the seven engines and carry the flight loads of everything above it.',
    how: 'LOX is loaded from ground tanks through the tower umbilical while it boils and vents; it is topped up until shortly before launch. In flight, helium keeps the gas space above the liquid (ullage) at a controlled pressure as the level falls. That pressure does two jobs: it gives the turbopumps enough inlet pressure to avoid cavitation, and it stiffens the thin wall against buckling. The walls are the airframe (an integral tank): the barrel carries thrust and bending, the pressure puts the wall in hoop tension.',
    why: `LOX is ${F.loxShare} of the booster's propellant mass and the denser of the two (${F.loxDensity} versus ${F.rp1Density} for RP-1). Putting it on top moves the centre of mass forward. A vehicle without fins is aerodynamically unstable (the air's side force acts ahead of the centre of mass), and a forward centre of mass shortens that destabilizing lever and lengthens the lever the engine gimbals steer with; the price is the downcomer through the fuel tank. The long column of LOX above the pumps also raises their inlet pressure when the vehicle accelerates.`,
    phases: [
      at('leo', 'pad', 'Filled with LOX that boils and vents; frost forms on the thin wall.'),
      at('leo', 'maxq', 'The pressurized shell carries peak bending loads.'),
      at('leo', 'meco', 'Near empty; the highest acceleration of the burn loads the domes.'),
      at('leo', 'boostback', 'The reserve LOX must be settled at the outlet before the relight.'),
    ],
    environment: `Cryogenic liquid at ${F.loxBoil} inside and warm humid air outside on the pad, which is why frost forms. In flight: axial compression from thrust, bending from wind and manoeuvres near maximum dynamic pressure, hoop tension from ullage pressure, sloshing, and an acceleration that grows to several g as the propellant drains.`,
    figures: [
      { label: 'LOX mass', value: F.s1Lox, note: `Mixture ratio ${F.mr} of ${F.s1Prop}` },
      { label: 'Tank volume', value: F.s1LoxVolume, note: 'Including 3 % ullage (dataset rule)' },
      { label: 'Liquid density / boiling point', value: `${F.loxDensity} / ${F.loxBoil}` },
      { label: 'Diameter / length (apex to apex)', value: `${F.diameter} / ${F.s1LoxTankLength}` },
      { label: 'LOX drawn by seven engines', value: F.s1LoxFlow, note: `${F.s1LoxVolumeFlow}, computed` },
    ],
    materials: mats('s1-lox-tank'),
    materialsWhy: 'Barrels are aluminium-lithium alloy: lower density and higher stiffness than conventional aluminium alloys, with strength and toughness that hold up (or improve) at cryogenic temperature. Domes are aluminium alloy 2219, chosen for its weldability and toughness at LOX temperature. Stainless steel is shown for comparison: documented designs use it for cryogenic tanks because it is strong at both very low and high temperature and cheap to work, at the cost of heavier walls. Spray-on foam is not used here because the booster is loaded shortly before launch and continuously topped up; long-duration cryogenic stages use it to slow boil-off.',
    manufacturing: 'Barrel panels are machined from thick plate into an orthogrid (a square pattern of ribs, with most of the metal removed), roll-formed to the tank curvature, and joined by friction-stir welding, which joins the metal without melting it and gives strong, low-distortion welds in aluminium-lithium. Domes are spun or welded from gores. The finished tank is proof pressure tested above its maximum operating pressure.',
    inspection: 'Every weld is X-rayed or scanned with phased-array ultrasound; the tank is proof tested and helium leak checked; dimensions are measured for buckling-sensitive roundness. Recovered tanks are re-inspected at welds and attachment points.',
    misconception: '"Tank walls must be thick to hold the pressure." The wall is only millimetres thick in most places. Internal pressure actually helps: like a sealed drink can that is hard to crush, the pressurized shell resists buckling under the enormous axial load, and the orthogrid adds stiffness where pressure alone is not enough.',
    ifAbsent: `A rocket carries its own oxygen because there is not enough air at altitude, and none in space, to burn the fuel. Without the LOX tank there is no oxidizer: ${F.loxShare} of the booster's propellant.`,
    depth: {
      quick: 'The big upper tank holds super-cold liquid oxygen. Its thin wall is also the rocket\'s body, kept stiff by the gas pressure inside.',
      engineering: `Hoop stress in a pressurized cylinder is σ = p·r / t, so a ${F.diameter} tank at a few bar needs only a few millimetres of wall for pressure. The limiting load is usually axial compression plus bending (buckling), where pressure stabilization and the orthogrid pattern raise the load the thin shell can carry. With the heavier propellant forward, the centre of mass sits closer to the centre of pressure, which lies ahead of it on a finless vehicle, so the gimbals need less deflection to hold the attitude against gusts.`,
      materials: 'Aluminium-lithium saves mass where the area is largest (the barrels); 2219 is used where welding complex shapes matters (the domes). Friction-stir welding is what makes aluminium-lithium practical: fusion welding it is difficult.',
    },
    demo: 'tank-drain',
    closeup: 'tank-wall',
    sources: ['nasa-al-li-crush', 'nasa-sp8007', 'nasa-isogrid', 'nasa-grc-stability', 'nasa-std-5001', 'saturn-v-flight-manual'],
  }),

  lesson({
    id: 's1-fuel-tank',
    summary: `The booster's lower tank, holding ${F.s1Rp1} of RP-1 kerosene at ambient temperature, with the LOX downcomer running straight through its centre.`,
    where: `Just above the thrust section, from ${F.st.s1FuelAftApex} to about ${F.st.s1FuelFwdApex} (${F.s1FuelTankLength} apex to apex), below the intertank. In the cutaway: the amber RP-1, the downcomer pipe down its middle, anti-slosh baffles, and the fuel outlets in the aft dome feeding the engine manifold.`,
    connections: ['lox-downcomer', 'thrust-structure', 's1-intertank', 'pressurization', 'engine', 'raceway', 'landing-legs'],
    function: 'Store the fuel for the seven engines, which also serves as their coolant, and carry the thrust of the whole cluster up into the rest of the vehicle.',
    how: 'RP-1 is loaded at ambient temperature and pressurized with helium. It leaves through outlets in the aft dome to a manifold feeding every turbopump. Because it sits directly on the thrust structure, its barrel wall is the path by which the engines\' thrust pushes the whole vehicle upward.',
    why: 'Kerosene is dense, easy to store and handle, and a good regenerative coolant. The two propellants must be kept apart until the injector: mixed, they would form a dangerous, shock-sensitive mixture, and LOX would freeze the kerosene. RP-1 is the lower tank because the denser, heavier LOX goes on top.',
    phases: [
      at('leo', 'pad', 'Loaded at ambient temperature before the LOX.'),
      at('leo', 'liftoff', 'Its walls carry the full thrust of the cluster into the vehicle.'),
      at('leo', 'meco', 'A reserve stays in the tank for the return burns.'),
      at('leo', 'landing-burn', 'The last of the reserve feeds the centre engine.'),
    ],
    environment: `Ambient-temperature fuel, but cold spots around the downcomer carrying LOX at ${F.loxBoil}. Axial compression is highest here, near the base, because the barrel carries the inertia of everything above it; bending at maximum dynamic pressure; and landing loads from the legs on recovery flights.`,
    figures: [
      { label: 'RP-1 mass', value: F.s1Rp1 },
      { label: 'Tank volume', value: F.s1Rp1Volume, note: 'Including 3 % ullage' },
      { label: 'RP-1 density', value: F.rp1Density, note: 'Room temperature' },
      { label: 'Length (apex to apex)', value: F.s1FuelTankLength },
    ],
    materials: mats('s1-fuel-tank'),
    materialsWhy: 'Aluminium-lithium barrels save mass on the largest areas; aluminium 2219 domes are easy to weld into complex curved shapes. The fuel tank does not need cryogenic toughness as much as the LOX tank does, but using the same alloys and processes for both tanks keeps production simple.',
    manufacturing: 'As for the LOX tank: machined orthogrid panels, friction-stir welded barrels, spun or welded domes, and a sealed penetration where the downcomer enters and leaves the tank. Proof and leak tests follow.',
    inspection: 'Weld X-ray or ultrasound, proof pressure, helium leak checks of every penetration, and cleanliness checks (particles in the fuel can block injector orifices or cooling channels).',
    misconception: '"RP-1 is just jet fuel." It is a kerosene refined to tighter limits, with less sulfur and fewer reactive compounds, so it can flow through hot cooling channels without leaving carbon deposits that would block them.',
    ifAbsent: 'Without the fuel tank there is no fuel and no coolant for the chamber walls, and the load path from the thrust structure up to the intertank and LOX tank would be missing its lowest link.',
    depth: {
      quick: 'The lower tank holds kerosene. The engines are right below it, so its walls also carry their push up into the rest of the rocket.',
      engineering: 'The barrel carries the inertial load (mass times acceleration plus gravity) of everything it supports above it: intertank, LOX tank and LOX, interstage, upper stage and payload. The fuel itself rests on the aft dome, which hands its load straight to the thrust structure. Internal pressure offsets part of the compression, as in the LOX tank; keeping the fuel above its minimum pump inlet pressure while it drains is the pressurization system\'s job.',
      materials: 'The same aluminium-lithium and 2219 family as the LOX tank, with welded penetrations for the downcomer and the fuel outlets.',
    },
    demo: 'feed-flow',
    closeup: 'tank-wall',
    sources: ['nasa-al-li-crush', 'edwards-fuels', 'sutton-rpe', 'nasa-sp8007'],
  }),

  lesson({
    id: 'lox-downcomer',
    summary: 'The downcomer is the large pipe that carries liquid oxygen from the upper tank down through the middle of the fuel tank to the engines.',
    where: `From the outlet in the LOX tank's aft dome (${F.st.s1LoxAftApex}), down through the intertank, then through the centre of the RP-1 tank to the engine LOX manifold in the thrust section: about ${F.downcomerLength} of pipe. In the cutaway it is the pale-blue line through the amber fuel.`,
    connections: ['s1-lox-tank', 's1-fuel-tank', 's1-intertank', 'turbopump', 'thrust-structure'],
    function: `Deliver about ${F.s1LoxFlow} of LOX (${F.s1LoxVolumeFlow}) to seven engines at full thrust with a steady, bubble-free flow.`,
    how: `A welded aluminium duct with flexible bellows joints and stainless flanges. The bellows let the pipe shrink when it chills (aluminium contracts about 0.4 % from room temperature to LOX temperature, so about ${F.downcomerContraction} over this length) and let the tanks and pipe move relative to one another under load. An anti-vortex baffle at the tank outlet stops a swirl from drawing gas into the line.`,
    why: 'It is the cost of placing LOX on top. The alternative, external lines along the outside of the fuel tank, needs aerodynamic covers and adds drag and heating; running the line through the fuel tank keeps a clean outer shape but must pass sealed through two domes.',
    phases: [
      at('leo', 'pad', 'Chilled and kept full of cold, bubble-free LOX before start.'),
      at('leo', 'liftoff', 'Carries the full LOX flow for seven engines.'),
      at('leo', 'boostback', 'Feeds three relit engines from the reserve.'),
    ],
    environment: `LOX at ${F.loxBoil} inside, warm kerosene outside. The long vertical column can trap vapour bubbles that erupt upward (geysering) if heat leaks in during the pad hold, and the liquid column can couple with the vehicle's lengthwise vibration (pogo).`,
    figures: [
      { label: 'Length', value: `about ${F.downcomerLength}`, note: 'From the LOX tank outlet to the thrust section, computed from the stations' },
      { label: 'LOX flow at full thrust', value: `${F.s1LoxFlow} (${F.s1LoxVolumeFlow})`, note: 'Computed' },
      { label: 'Thermal contraction on chilling', value: `about ${F.downcomerContraction}`, note: 'About 0.4 % for aluminium (NIST data)' },
    ],
    materials: mats('lox-downcomer'),
    materialsWhy: 'The duct is aluminium alloy 2219: light, weldable and tough at LOX temperature, like the tanks it joins. The bellows and flanges are stainless steel, which tolerates the repeated flexing of convolutions and holds bolt loads and seals at cryogenic temperature.',
    manufacturing: 'Pipe sections are formed and welded, bellows welded in, and flanges fitted with cryogenic seals. The penetrations through the fuel tank domes are welded or sealed and leak checked.',
    inspection: 'Weld X-ray, cryogenic leak checks, and bellows inspection for fatigue cracks. On recovered boosters the bellows are a life-limited item.',
    misconception: '"A pipe carrying cold liquid only needs to be strong." The hard problems are thermal and dynamic: contraction when it chills, heat leaking in from the fuel around it (which can make vapour and geysering), and pogo. Documented designs have injected helium into long LOX lines on the pad to prevent geysering and fitted gas-filled accumulators to suppress pogo.',
    ifAbsent: 'With LOX on top and no downcomer, the oxygen could not reach the engines except through external lines; or the tanks would be swapped, moving the centre of mass aft.',
    depth: {
      quick: 'Because the oxygen tank is on top, a big pipe carries the oxygen down through the middle of the fuel tank to the engines.',
      engineering: `Flow speed and diameter trade pressure loss against mass. Under an acceleration a, the liquid column adds ρ·a·h of pressure at the pump inlet, which helps against cavitation but also makes the column a spring-mass system that can couple with the structure (pogo). A documented kerosene first stage used the same layout: LOX forward, suction lines through the fuel tank.`,
      materials: 'Aluminium duct for mass and compatibility; stainless bellows where flexing and sealing matter. Thermal contraction drives the design as much as pressure does.',
    },
    demo: 'feed-flow',
    sources: ['saturn-v-flight-manual', 'nasa-pogo', 'nist-cryo', 'huzel-huang-sp125'],
  }),

  lesson({
    id: 'pressurization',
    summary: 'The helium pressurization system keeps both tanks at the right pressure as they drain, using helium stored at very high pressure in carbon-wrapped bottles (COPVs) submerged in the liquid oxygen.',
    where: 'The COPVs hang on brackets near the top of the LOX tank, submerged when it is full, so the LOX keeps them cold. High-pressure lines run to the engines\' heat exchangers and back, then to the perforated diffusers under the forward dome of each tank. Some lines travel in the external raceway.',
    connections: ['s1-lox-tank', 's1-fuel-tank', 'gas-generator', 'raceway', 'turbopump', 'service-tower'],
    function: `Replace the volume of propellant leaving the tanks (about ${F.s1VolumeFlow} at full thrust, computed) with gas, so the ullage pressure stays at its set value from liftoff to cutoff.`,
    how: `Helium at tens of megapascals flows through control valves, is warmed in the heat-exchanger coils in the engines' exhaust ducts (warm gas occupies more volume per kilogram, so less helium is needed), and enters the tanks through diffusers that spread it gently over the liquid. Helium stays a gas at LOX temperature (it boils at about 4 K) and is inert. Storing it cold is the trick: at the same pressure, helium at LOX temperature is about ${F.heliumDensityRatio} times denser than at room temperature (ideal gas), so a bottle holds about three times more.`,
    why: 'Pumps need a minimum inlet pressure or the liquid flashes into vapour bubbles and the pump cavitates. The thin tank walls need internal pressure to resist buckling. Without pressurant, a draining sealed tank would pull a partial vacuum and could collapse.',
    phases: [
      at('leo', 'pad', 'The COPVs are charged and the tanks pressurized to flight pressure in the final minutes.'),
      at('leo', 'maxq', 'Tank pressure stabilizes the shell against peak bending.'),
      at('leo', 'meco', 'The ullage is largest and pressurant use highest near cutoff.'),
      at('leo', 'booster-coast', 'The tanks stay pressurized for stiffness and for the next relight.'),
    ],
    environment: 'Bottles at tens of megapascals, immersed in liquid oxygen, shaken by launch vibration. A COPV failure releases a great deal of stored energy, and carbon composite in contact with oxygen demands careful qualification: oxygen trapped in an overwrap is an ignition hazard.',
    figures: [
      { label: 'Helium density gain when stored cold', value: `about ${F.heliumDensityRatio} ×`, note: 'Ideal gas, room temperature (293 K) versus LOX temperature, same pressure' },
      { label: 'Volume to refill per second at full thrust', value: F.s1VolumeFlow, note: 'LOX plus RP-1, computed' },
      { label: 'Storage pressure', value: 'about 30 MPa', note: 'Illustrative, the usual order for helium COPVs: about a hundred times the few-bar tank pressure' },
    ],
    materials: mats('pressurization'),
    materialsWhy: 'A COPV is a thin gas-tight titanium liner wrapped in carbon fibre. The fibres carry most of the pressure load (they are much stronger per kilogram than any metal); the liner only has to seal, because fibre composites alone leak gas. Titanium lines are strong and light at high pressure.',
    manufacturing: 'The liner is spun and welded, then carbon-fibre tows soaked in resin are wound over it in hoop and helical patterns and cured. A first over-pressurization (autofrettage) yields the liner slightly so it sits in compression at rest, improving its fatigue life. Every vessel is proof tested.',
    inspection: 'Proof testing with acoustic-emission monitoring (listening for fibre breaks), visual inspection for impact damage (which may not show on the surface), strict handling rules, and records of every pressure cycle for fatigue and stress-rupture life.',
    misconception: '"The tank pressure pushes the propellant into the engine." In a pump-fed engine the tanks are at only a few bar; the turbopumps do the real work. Tank pressure just keeps the pumps from cavitating and the walls from buckling.',
    ifAbsent: 'The ullage pressure would fall as the propellant drained: pumps would cavitate and lose thrust, and the thin tanks would lose the pressure that stiffens them.',
    depth: {
      quick: 'Helium gas from bottles inside the oxygen tank fills the space the propellant leaves, keeping the tanks stiff and the pumps well fed.',
      engineering: 'The pressurant mass needed is proportional to p·V / (R·T) of the final ullage: heating the helium before it enters the tank reduces the mass needed, cold storage raises how much fits in a bottle. Alternatives include autogenous pressurization (vaporized propellant, e.g. heated oxygen for the LOX tank). A documented kerosene first stage also stored its helium in bottles inside the LOX tank.',
      materials: 'Carbon fibre for hoop strength per kilogram, titanium for a gas-tight liner and lines. COPVs trade low mass for sensitivity to impact damage and a stress-rupture life that must be tracked.',
    },
    demo: 'tank-pressure',
    sources: ['nasa-copv', 'huzel-huang-sp125', 'saturn-v-flight-manual', 'nasa-std-5001'],
  }),

  lesson({
    id: 's2-tanks',
    summary: `The upper stage's two propellant tanks, RP-1 below and LOX above, built as one short cylinder divided by a common bulkhead and holding ${F.s2Prop} of propellant.`,
    where: `The white upper-stage body from ${F.st.s2FuelAftApex} to about ${F.st.s2LoxFwdApex} (${F.s2TankLength} apex to apex), between the thrust cone and E-1V below and the avionics ring and payload adapter above. In the cutaway: RP-1 in the lower part, the curved common bulkhead bulging down into it, LOX above.`,
    connections: ['common-bulkhead', 'vacuum-engine', 'avionics', 'payload-adapter', 's2-rcs', 'interstage'],
    function: `Store ${F.s2Lox} of LOX and ${F.s2Rp1} of RP-1 for the E-1V and deliver them bubble-free, including after long weightless coasts.`,
    how: 'Helium pressurizes both tanks. During powered flight the propellant sits at the bottom of each tank. During a coast the stage is in free fall and the liquid floats, clings to walls and sloshes; before a restart the settling thrusters give a small push so the liquid collects over the outlets. Baffles damp sloshing. The tank wall is bare aluminium with no foam, so during a coast the LOX slowly warms in sunlight; keeping coasts short, and turning the stage so no side stays in the Sun, limits that.',
    why: 'The upper stage\'s mass travels all the way to orbit, so every kilogram of structure costs almost a kilogram of payload. A short, light tank structure with a common bulkhead saves both length and mass compared with separate tanks and an intertank.',
    phases: [
      at('leo', 'upper-burn', 'Drained by the E-1V as the stage builds orbital speed.'),
      at('gto', 'parking-coast', 'Propellant floats in free fall; the LOX slowly warms.'),
      at('gto', 'restart', 'Settling thrusters collect the liquid over the outlets.'),
      at('lunar', 'tli', 'The last large burn draws the tanks down.'),
    ],
    environment: `Cryogenic LOX at ${F.loxBoil} next to ambient RP-1; the payload's inertia pressing down during burns; weightless coasts of tens of minutes in sunlight and shadow; and near the end of a burn an acceleration that would reach about ${F.s2EndAccelLeo} at full thrust with only the empty stage and satellite left (LEO mission, computed), so guidance throttles the engine back near cutoff to limit it (see the telemetry).`,
    figures: [
      { label: 'LOX / RP-1', value: `${F.s2Lox} / ${F.s2Rp1}` },
      { label: 'Tank volumes', value: `${F.s2LoxVolume} / ${F.s2Rp1Volume}`, note: 'Including 3 % ullage' },
      { label: 'Length (apex to apex)', value: F.s2TankLength },
      { label: 'Stage dry mass', value: F.s2Dry },
    ],
    materials: mats('s2-tanks'),
    materialsWhy: 'Aluminium-lithium barrels and 2219 domes, as on the booster: light, stiff and tough at cryogenic temperature. On the upper stage the mass saving of aluminium-lithium is worth even more, since stage mass trades almost one-for-one with payload.',
    manufacturing: 'Orthogrid barrel panels and friction-stir welding as on the booster; the common bulkhead is built separately and welded in. Proof and leak tests of both tanks and of the bulkhead in both pressure directions.',
    inspection: 'Weld inspection, proof and leak tests, and checks of the bulkhead core for disbonds and leaks.',
    misconception: '"In orbit the fuel sits at the bottom of the tank." In free fall there is no bottom: the liquid floats and wanders. The stage must settle it before an engine can restart.',
    ifAbsent: 'Without upper-stage tanks there is no second stage; one stage alone cannot reach orbit with a useful payload using these propellants.',
    depth: {
      quick: 'The upper stage stores its oxygen and kerosene in one short tank split by a shared wall. In space the liquid floats, so small thrusters push it back into place before restarting the engine.',
      engineering: `In the ideal rocket equation for the LEO mission, the stage delivers about ${F.leoS2} (${F.s2Prop} of propellant, ${F.e1vIsp}). Adding 100 kg to the upper stage costs about ${F.tradeS2} of LEO payload, versus about ${F.tradeS1} for 100 kg added to the booster (ideal estimate at fixed total velocity change). That is why upper-stage structures are built so lean.`,
      materials: 'The same aluminium alloys as the booster, but with more reason to save every kilogram; the common bulkhead is the key mass saving.',
    },
    demo: 'tank-drain',
    closeup: 'tank-wall',
    sources: ['nasa-al-li-crush', 'nasa-grc-rocket-eq', 'huzel-huang-sp125', 'nasa-ceus'],
  }),

  note({
    id: 's2-rcs',
    summary: 'Small nitrogen cold-gas thrusters on the upper stage that control roll during burns, hold attitude during coasts, and settle the propellant before a restart.',
    function: 'A single gimballed engine can steer pitch and yaw but not roll, so these thrusters control roll during burns. During coasts they point the stage (and payload) and, before a restart, fire together toward the rear to give a small forward acceleration that collects the floating propellant over the tank outlets.',
    why: 'Cold gas is simple, clean near the payload and can fire any number of times. Settling is essential: a pump that swallows gas instead of liquid at start can overspeed and fail.',
    materials: mats('s2-rcs'),
    phases: [
      at('leo', 'coast', 'Settles the propellant before the circularization restart, then holds the attitude for payload separation.'),
      at('gto', 'restart', 'The settling burn before the E-1V restarts.'),
      at('lunar', 'tli', 'Settles propellant before the restart for trans-lunar injection.'),
      at('leo', 'staging', 'Controls attitude between separation and upper-stage ignition.'),
    ],
    sources: ['sutton-rpe', 'huzel-huang-sp125'],
  }),
];
