/**
 * Payload and spacecraft lessons: the satellite bus and its arrays, antenna and attitude
 * control, the crew capsule and its docking system, and the station.
 */
import type { PartLesson, PartNote } from '../types';
import { at, lesson, mats, note } from './util';
import { F } from './derived';

export const PAYLOAD: (PartLesson | PartNote)[] = [
  lesson({
    id: 'satellite-bus',
    summary: 'The satellite bus is the spacecraft\'s body: the structure and the subsystems (power, thermal control, attitude control, propulsion, radio and computers) that keep its instrument working in orbit.',
    where: `Inside the fairing on top of the payload adapter. The Earth-observation satellite (${F.leoSatMass}) is a box about 2.3 × 2.3 × 3.6 m (illustrative model) wrapped in gold and silver MLI, with its instrument and sun baffle on the Earth-facing side, star trackers, folded solar-array wings on two sides, and a separation ring at its base.`,
    connections: ['payload-adapter', 'solar-arrays', 'antenna', 'attitude-thrusters', 'mli-blankets', 'fairing', 'apogee-engine'],
    function: 'Carry the payload through launch, then provide power, pointing, temperature control, communication and data handling for years in orbit.',
    how: 'A central cone or cylinder carries launch loads straight down into the adapter ring; flat sandwich panels around it carry the equipment. Solar arrays charge batteries; reaction wheels and thrusters point the spacecraft; radiators and MLI hold temperatures; the onboard computer runs everything and talks to the ground through the antenna.',
    why: 'Launch lasts minutes but sets the structural design: loads of several g and intense vibration. Orbit lasts years and sets everything else: power, heat, pointing, radiation.',
    phases: [
      at('leo', 'deploy', 'Released from the adapter to fly on its own.'),
      at('leo', 'arrays', 'Unfolds its arrays and makes first contact.'),
      at('gto', 'transfer-coast', 'Coasts for hours up to apogee.'),
      at('gto', 'circularize', 'Fires its apogee engine at three apogees to reach geostationary orbit.'),
      at('lunar', 'flyby', 'The probe\'s bus carries it past the Moon\'s trailing side.'),
    ],
    environment: `Launch loads, vibration and noise inside the fairing, then vacuum, sunlight and shadow every ${F.leoPeriod} in low orbit, radiation, and in low orbit the erosion of atomic oxygen.`,
    figures: [
      { label: 'Masses in this simulator', value: `${F.leoSatMass} (Earth observation), ${F.gtoSatMass} (geostationary communications), ${F.lunarProbeMass} (lunar probe)` },
      { label: `Orbit period at ${F.leoAlt}`, value: F.leoPeriod, note: `${F.orbitsPerDay} orbits per day, computed` },
      { label: `Gravity at ${F.leoAlt}`, value: `${F.gravityAt400} of the surface value`, note: 'Inverse-square law, computed' },
    ],
    materials: mats('satellite-bus'),
    materialsWhy: 'The primary cone is aluminium 2219: strong, easy to machine and join, and a good path for heat. Equipment panels are carbon-fibre sandwich for stiffness per kilogram and dimensional stability. MLI blankets wrap the bus to control radiation heat flow.',
    manufacturing: 'Structure machined and bonded, panels built as sandwich, units bolted on and harnessed, blankets fitted by hand, all in a clean room. The finished spacecraft is vibration tested, acoustic tested and thermal-vacuum tested before shipping to the launch site.',
    inspection: 'Functional tests of every subsystem after each environmental test, cleanliness checks, mass-property measurement (mass, centre of mass, inertia), and a fit check with the adapter.',
    misconception: `"Satellites float because there is no gravity up there." At ${F.leoAlt} gravity is still about ${F.gravityAt400} of its surface value. A satellite is falling all the time; it moves sideways so fast (${F.leoSpeed}) that the Earth curves away beneath it as fast as it falls.`,
    ifAbsent: 'An instrument without a bus would have no power, pointing, temperature control or radio: it would be dead within hours.',
    depth: {
      quick: 'The satellite\'s body keeps its instrument alive: power from the Sun, a radio to talk to Earth, thrusters and wheels to point it, and blankets to keep it at the right temperature.',
      engineering: 'Structural design is driven by the launch environment (quasi-static load factors, sine and random vibration, acoustics, separation shock); in orbit the drivers are power balance through eclipse, heat rejection, pointing stability and radiation dose. Mass, centre of mass and stiffness are specified by the launch vehicle.',
      materials: 'Aluminium for load-carrying structure and heat paths, composite sandwich for stiff, stable panels, MLI for thermal control. Material outgassing in vacuum is controlled so it does not fog optics.',
    },
    demo: 'spacecraft-ops',
    sources: ['nasa-sst-soa', 'nasa-bsf-3'],
  }),

  lesson({
    id: 'solar-arrays',
    summary: 'Solar arrays are the fold-out wings of solar cells that power a spacecraft; stowed flat for launch, they unfold in orbit and turn to face the Sun.',
    where: 'On the satellite, two wings folded against its sides during launch (a yoke plus several hinged panels each). On the capsule configuration, two wings on the service module. Look for the dark cell grid with bright busbars.',
    connections: ['satellite-bus', 'service-module', 'attitude-thrusters', 'antenna'],
    function: 'Convert sunlight into electricity for the spacecraft and charge the batteries that carry it through Earth\'s shadow.',
    how: 'Photovoltaic cells (multi-junction cells on modern spacecraft) turn a fraction of the sunlight into electrical power. After separation, release mechanisms free the folded panels and spring-driven hinges with dampers unfold them in sequence: yoke first, then panels. A drive then turns the wing to track the Sun as the spacecraft orbits.',
    why: `Sunlight above the atmosphere delivers about ${F.solarIrradiance} and never runs out, so it is the natural energy source near Earth. Arrays must be folded for launch to fit inside the fairing and survive vibration, and deployed in orbit to present a large area. In a ${F.leoAlt} orbit up to about ${F.eclipseMin} of each ${F.leoPeriod} orbit is in shadow (computed), so batteries must carry the load then.`,
    phases: [
      at('leo', 'arrays', 'Unfold in sequence and turn toward the Sun.'),
      at('station', 'capsule-sep', 'The service module\'s wings deploy after separation.'),
      at('lunar', 'cruise', 'Power the probe on its three-day coast.'),
    ],
    environment: 'Launch vibration while folded, then vacuum, full sunlight and deep cold in Earth\'s shadow, cycling every orbit; radiation that slowly degrades the cells; and deployment shocks.',
    figures: [
      { label: 'Sunlight above the atmosphere', value: `about ${F.solarIrradiance}`, note: 'Total solar irradiance (Kopp and Lean, 2011)' },
      { label: `Shadow per orbit at ${F.leoAlt}`, value: `up to about ${F.eclipseMin}`, note: 'Orbit plane containing the Sun direction, computed' },
    ],
    materials: mats('solar-arrays'),
    materialsWhy: 'Substrate panels are carbon-fibre sandwich: very stiff and light, so the wing stays flat and its first vibration frequency stays high, and carbon fibre\'s near-zero thermal expansion limits warping between sunlight and shadow.',
    manufacturing: 'Cells are laid down, soldered or welded into strings and bonded to the panels with cover glass; panels are hinged together, with hold-down points for launch. Deployment is tested on the ground with gravity offloading (the panels are supported so they move as if weightless).',
    inspection: 'Electrical tests of each string, visual inspection for cracked cells, and deployment tests before and after vibration testing.',
    misconception: '"Satellites in orbit are always in sunlight." In low orbit a spacecraft is in Earth\'s shadow for a large part of every orbit, which is why it carries batteries.',
    ifAbsent: 'On batteries alone the spacecraft would work only for hours.',
    depth: {
      quick: 'Folded solar panels open in orbit and turn toward the Sun to make electricity; batteries keep the spacecraft running in Earth\'s shadow.',
      engineering: 'Array power = irradiance × area × cell efficiency × packing and degradation factors × cos(Sun angle). The array is sized for end-of-life power at the worst Sun angle, plus battery recharge during the sunlit part of each orbit.',
      materials: 'Composite substrates for flatness and stability, cover glass against radiation, flexible interconnects that tolerate thousands of thermal cycles.',
    },
    demo: 'spacecraft-ops',
    sources: ['nasa-sst-soa', 'kopp-lean-tsi'],
  }),

  lesson({
    id: 'antenna',
    summary: 'The communications antenna is the dish that concentrates the spacecraft\'s radio signal into a narrow beam toward the ground (and receives commands).',
    where: 'On the satellite, a dish about 1 m across on a deployable boom (illustrative model); on the geostationary satellite, large folded reflectors on its sides; on the lunar probe, a high-gain dish.',
    connections: ['satellite-bus', 'solar-arrays', 'attitude-thrusters'],
    function: 'Send data (images, telemetry) to ground stations and receive commands, with enough signal strength to cross hundreds or thousands of kilometres, or much more for the Moon.',
    how: `A parabolic reflector gathers radio waves into (or out of) its focus, like a mirror for light. The bigger the dish compared with the wavelength, the narrower the beam and the higher the gain. At an X-band frequency of 8.4 GHz the wavelength is about ${F.xBandWavelength} (computed), so a 1 m dish is many wavelengths across; its surface must be accurate to a small fraction of the wavelength. The spacecraft must point it at the ground station during each pass.`,
    why: 'A concentrated beam lets a spacecraft with limited power deliver a strong signal at a distant ground station; a low-gain antenna that radiates in all directions can only carry low data rates.',
    phases: [
      at('leo', 'arrays', 'Deploys and makes first contact with the ground.'),
      at('lunar', 'cruise', 'Keeps contact across hundreds of thousands of kilometres.'),
      at('gto', 'transfer-coast', 'Keeps the ground in touch during the climb to apogee.'),
    ],
    environment: 'Large temperature swings between sunlight and shadow, which can warp a reflector; vacuum; launch loads while folded.',
    figures: [
      { label: 'Wavelength at 8.4 GHz (X band)', value: F.xBandWavelength, note: 'Speed of light ÷ frequency, computed' },
      { label: 'Dish diameter', value: 'about 1 m', note: 'Earth-observation satellite, illustrative model' },
    ],
    materials: mats('antenna'),
    materialsWhy: 'The reflector is carbon-fibre sandwich because carbon fibre expands very little with temperature, so the dish keeps its precise shape as it moves between sunlight and shadow; it is also stiff and light on a long boom.',
    manufacturing: 'Laid up on a precision mould, cured, and measured for surface accuracy; the reflective surface is the conductive carbon itself or a thin metallic coating. The boom and hinge are tested for deployment accuracy.',
    inspection: 'Surface-accuracy measurement (photogrammetry), radio-frequency tests on an antenna range, and deployment tests.',
    misconception: '"An antenna broadcasts in all directions." A dish concentrates the signal into a narrow beam, which is why the satellite has to point it at the ground station.',
    ifAbsent: 'The spacecraft could not return its data; a low-gain antenna could carry commands and housekeeping at low rate only.',
    depth: {
      quick: 'The dish works like a mirror for radio waves, focusing the signal into a narrow beam aimed at Earth.',
      engineering: 'Antenna gain ≈ η·(π·D/λ)²; beamwidth ≈ 70·λ/D degrees. Link budget: received power grows with transmit power and both antennas\' gains and falls with the square of distance. Surface errors reduce gain rapidly once they approach a sizeable fraction of λ.',
      materials: 'Near-zero thermal expansion (carbon fibre) keeps the reflector accurate; stiffness keeps the boom from wobbling after slews.',
    },
    demo: 'spacecraft-ops',
    sources: ['nasa-sst-soa'],
  }),

  lesson({
    id: 'attitude-thrusters',
    summary: 'Small thrusters and spinning reaction wheels that point the spacecraft (its instrument, arrays and antenna) and occasionally nudge its orbit.',
    where: 'On the satellite, small thruster clusters at the corners of the bus; reaction wheels inside the bus (visible in the cutaway). On the capsule, thrusters around its sides and on the service module.',
    connections: ['satellite-bus', 'solar-arrays', 'antenna', 'capsule', 'service-module', 'docking-system'],
    function: 'Stop the tumble after separation, point the spacecraft precisely, unload momentum from the wheels, and make small orbit corrections; on the capsule, fly the approach and hold attitude during entry.',
    how: 'A reaction wheel is a motor-driven flywheel: speeding it up one way turns the spacecraft the other way (angular momentum is conserved), giving smooth, fine pointing with no propellant. Small external torques (from the thin atmosphere, sunlight pressure and gravity differences across the spacecraft) slowly build up wheel speed, so thrusters or magnetic torquers periodically unload it. The small thrusters are monopropellant: hydrazine flows over a heated catalyst bed and decomposes into hot gas, with no igniter.',
    why: 'A spacecraft must point its instrument at the target, its arrays at the Sun and its antenna at Earth. After separation it is also usually rotating slowly and must be stabilized before its arrays can deploy.',
    phases: [
      at('leo', 'deploy', 'Stabilizes the satellite after separation.'),
      at('leo', 'arrays', 'Turns the satellite so the arrays can find the Sun.'),
      at('gto', 'circularize', 'Holds the pointing during each apogee-engine burn and turns the satellite between them.'),
      at('station', 'approach', 'The capsule\'s thrusters fly the final approach.'),
      at('return', 'undock', 'Small burns back the capsule away from the station.'),
      at('return', 'entry', 'Roll the capsule to steer its lift during entry.'),
    ],
    environment: 'Vacuum and thermal cycling; propellant lines kept warm by heaters so the hydrazine does not freeze; years of operation with millions of wheel revolutions.',
    figures: [
      { label: 'Monopropellant thruster specific impulse', value: 'about 220 s', note: 'Typical for hydrazine thrusters (Sutton & Biblarz)' },
    ],
    materials: mats('attitude-thrusters'),
    materialsWhy: 'Propellant tanks and lines are titanium: strong for their weight and compatible with hydrazine for years. Thruster chambers are nickel superalloy (or other high-temperature alloys) to survive the hot decomposition gas pulse after pulse.',
    manufacturing: 'Welded titanium tanks with diaphragms or surface-tension devices that deliver bubble-free propellant in weightlessness; thrusters machined and welded; wheels balanced and run in.',
    inspection: 'Leak checks of the propulsion system, thruster hot-fire acceptance tests, wheel run-in and vibration signature tests.',
    misconception: '"Spacecraft need thrusters to turn." Reaction wheels turn the spacecraft by spinning up internally, with no propellant; thrusters are needed only to dump the momentum the wheels accumulate and for larger manoeuvres.',
    ifAbsent: 'The spacecraft would tumble after separation, unable to point its arrays at the Sun or its antenna at Earth.',
    depth: {
      quick: 'Spinning wheels inside the satellite turn it smoothly; small thrusters stop tumbling and help when the wheels are saturated.',
      engineering: 'Angular momentum bookkeeping: H_spacecraft + H_wheels = constant unless an external torque acts. Wheels saturate at their maximum speed; momentum dumping uses thrusters or magnetorquers. Monopropellant thrusters trade specific impulse for simplicity and very small, repeatable impulse bits.',
      materials: 'Titanium for long-term propellant compatibility, high-temperature alloys for thruster chambers.',
    },
    demo: 'spacecraft-ops',
    sources: ['nasa-sst-soa', 'sutton-rpe'],
  }),

  lesson({
    id: 'capsule',
    summary: 'The crew capsule is the blunt, cone-shaped pressure vessel that carries people to orbit and brings them home, protected by its heat shield, tiles and parachutes.',
    where: `On top of the service module under the abort tower on the capsule configuration: ${F.capsuleDiameter} across the base, ${F.capsuleHeight} tall, sidewalls at ${F.capsuleSidewall}. Windows and the hatch are in the tiled backshell, the docking system is under the hinged nose cone, and the parachutes are packed in the forward bay. The uncrewed research capsule rides the booster alone on the suborbital flight.`,
    connections: ['heat-shield', 'backshell-tps', 'parachutes', 'docking-system', 'service-module', 'launch-abort-system', 'attitude-thrusters'],
    function: 'Provide a shirt-sleeve cabin at about sea-level pressure, carry the crew\'s seats, controls and life support, and form the entry vehicle that survives the return.',
    how: 'The welded pressure vessel holds cabin air against vacuum, putting the walls in tension like a balloon. Around it the heat shield, backshell tiles and parachute bay are attached. The capsule\'s centre of mass is placed slightly off its axis, so in the airflow it flies at a small angle and produces some lift; rolling with its thrusters points that lift up, down or sideways to steer toward the splashdown point and to spread out the deceleration.',
    why: 'A blunt shape is the most reliable way to survive entry from orbit: the shock wave stands off from the base and carries most of the heat away. Keeping the capsule small (everything else rides in the service module) keeps the heat shield small.',
    phases: [
      at('station', 'pad', 'The crew boards from the access arm.'),
      at('station', 'docking', 'Docks to the station.'),
      at('return', 'entry', 'Flies base-first with a small offset to generate lift.'),
      at('return', 'splashdown', 'Lands in the sea under three parachutes.'),
      at('suborbital', 'apogee', 'The research capsule floats over the top in free fall.'),
    ],
    environment: `Launch loads, abort accelerations, vacuum, entry heating and several g of deceleration, parachute opening shocks, and water impact. At entry it carries about ${F.capsuleKE} of kinetic energy relative to the air (${F.capsuleMass} at ${F.entryAir}, computed).`,
    figures: [
      { label: 'Base diameter / height', value: `${F.capsuleDiameter} / ${F.capsuleHeight}` },
      { label: 'Sidewall angle', value: F.capsuleSidewall },
      { label: 'Mass at entry', value: F.capsuleMass, note: 'With crew and cargo' },
      { label: 'Kinetic energy at entry', value: `about ${F.capsuleKE}`, note: `About ${F.capsuleTNT}, computed` },
    ],
    materials: mats('capsule'),
    materialsWhy: 'The pressure vessel is welded aluminium-lithium: light and tough, with good fatigue behaviour for repeated pressurization. Window frames and attachment fittings are titanium, whose strength and low thermal expansion suit parts that join glass and carry concentrated loads.',
    manufacturing: 'Machined and formed panels are welded into the pressure vessel (friction-stir welding for aluminium-lithium), openings reinforced, fittings installed; the vessel is proof-pressure and leak tested before thermal protection is added.',
    inspection: 'Weld X-ray, proof and leak tests, window inspection, and after each flight a detailed survey of the structure for corrosion from seawater.',
    misconception: '"Capsules heat up on entry because of friction with the air." The heating comes mainly from air squeezed and heated in the shock wave ahead of the base. The capsule flies base-first precisely so that shock stands off and carries most of that heat away.',
    ifAbsent: 'There would be no habitable, returnable vehicle for the crew.',
    depth: {
      quick: 'The capsule is the part the crew rides in. It comes home base-first, protected by its heat shield, and lands under parachutes.',
      engineering: 'Lift-to-drag ratio of a capsule is small (a few tenths) but lets bank-angle steering control the landing point and keep peak deceleration moderate. The pressure vessel sees hoop stress σ = p·r/t with p ≈ 101 kPa; windows, hatches and the docking tunnel are the design challenges.',
      materials: 'Aluminium-lithium for the pressure shell, titanium for fittings; thermal protection is a separate layered system.',
    },
    demo: 'capsule-return',
    sources: ['allen-eggers', 'nasa-ablators', 'nasa-bsf-3'],
  }),

  lesson({
    id: 'docking-system',
    summary: 'The docking system is the ring mechanism on the capsule\'s nose that catches the station\'s port gently (soft capture), then pulls the two together into an airtight seal (hard capture).',
    where: 'On the capsule\'s apex under the hinged nose cone, which swings open before the approach. The station\'s matching port faces straight down toward Earth.',
    connections: ['capsule', 'backshell-tps', 'attitude-thrusters', 'parachutes'],
    function: 'Join the capsule to the station structurally and airtight so the crew can open the hatches, and later release it for the trip home.',
    how: `Soft capture: a ring on the capsule, carried on dampers, meets the station's ring; guide petals align the two and capture latches catch. The dampers absorb the small remaining relative motion. Hard capture: the soft ring retracts, drawing the capsule in until structural hooks around both rings close and compress the seals. After leak checks, the hatches open.`,
    why: `Docking must tolerate small misalignments and relative velocities without large loads on either vehicle. The final closing speed in this mission is ${F.closingSpeed} or less, slower than a slow walk.`,
    phases: [
      at('station', 'approach', 'The nose cone opens and the ring is extended for the approach.'),
      at('station', 'docking', 'Soft capture, then hard capture.'),
      at('return', 'undock', 'Hooks open and springs push the capsule away.'),
    ],
    environment: 'Vacuum and thermal cycling, small but precise contact loads at capture, and the full structural loads of two joined spacecraft afterwards; seals must hold cabin pressure for months.',
    figures: [
      { label: 'Final closing speed', value: `${F.closingSpeed} or less`, note: 'Mission target in this simulator' },
    ],
    materials: mats('docking-system'),
    materialsWhy: 'The docking ring and latches are aluminium 2219: light, machinable to precise interfaces and stiff. Hooks and springs are stainless steel, strong and wear resistant where parts slide, latch and carry concentrated load.',
    manufacturing: 'Precision machining of rings and mechanisms, assembly with seals and sensors, and testing of both halves against each other (and against a standard reference) on a motion simulator.',
    inspection: 'Functional capture tests across the range of misalignments, seal leak tests, and inspection of hooks and latches after each docking.',
    misconception: '"The capsule just flies straight at the station and latches on." Orbital motion makes straight-line flying impossible without constant thrusting; the approach is a planned sequence of burns and hold points, and the contact is gentle.',
    ifAbsent: 'The crew could reach the station only by spacewalk, and the capsule could not stay attached as a lifeboat.',
    depth: {
      quick: 'A soft ring catches the station\'s port gently; then hooks pull the two together airtight so the crew can float through.',
      engineering: 'Capture envelope: lateral and angular misalignment, closing speed and rates that the mechanism can absorb. Energy to absorb is ½·m_rel·v² with the reduced mass of the two vehicles; the dampers are sized for it. An androgynous standard interface lets any two compatible vehicles dock.',
      materials: 'Aluminium for large precise rings, stainless steel for hooks and springs, elastomer seals for air tightness.',
    },
    sources: ['idss', 'nasa-ntrs-rendezvous'],
  }),

  note({
    id: 'station',
    summary: `The orbital station the capsule visits: pressurized modules joined at a node, with a truss carrying large solar-array wings and radiators, in a ${F.leoAlt} circular orbit.`,
    function: `It is the docking target. The station orbits at ${F.leoAlt} in the launch plane (inclination ${F.inclination}; the launch is timed so the pad lies in its plane), at about ${F.leoSpeed}, once every ${F.leoPeriod}. Its docking port faces straight down toward Earth, for an approach from below along the radial line.`,
    why: 'Rendezvous means matching the station\'s orbit exactly: same plane, same altitude, same place at the same time. A capsule cannot simply point at it and fly straight there; it must catch up by orbital mechanics.',
    materials: mats('station'),
    phases: [
      at('station', 'phasing', 'The capsule catches up from a lower, faster orbit.'),
      at('station', 'approach', 'The final approach along the radial line from below.'),
      at('station', 'docking', 'Soft capture and hard capture at its nadir port.'),
      at('return', 'undock', 'The capsule leaves it to begin the return.'),
    ],
    sources: ['nasa-ntrs-rendezvous', 'nasa-bsf-3'],
  }),
];
