/**
 * Propulsion lessons: the first-stage engine cluster, the E-1 engine and its internals, the
 * E-1V vacuum engine, the satellite apogee engine and the capsule's service module.
 */
import type { PartLesson, PartNote } from '../types';
import { at, lesson, mats, note } from './util';
import { F } from './derived';

export const PROPULSION: (PartLesson | PartNote)[] = [
  lesson({
    id: 's1-engine-cluster',
    summary: `The seven E-1 engines at the base of the booster, one in the centre and six in a ring, which together push the whole vehicle off the pad with ${F.s1ThrustSL} of thrust at sea level.`,
    where: `At the very bottom of the first stage. The nozzle exits define the model's zero height; each engine hangs from its gimbal ${F.st.s1Gimbal} higher, bolted to the thrust structure. The six outer engines sit on a ${F.ringRadius} radius ring around the centre engine, and only their lower bells show below the base heat shield at ${F.st.s1HeatShield}. Neighbouring nozzle lips are only about ${F.nozzleLipGap} apart.`,
    connections: ['engine', 'thrust-structure', 'base-heat-shield', 'tvc-actuators', 'lox-downcomer', 's1-fuel-tank', 'landing-legs'],
    function: 'Produce the booster\'s thrust, steer the vehicle by swinging the engines, and on recovery flights relight a few engines at a time for the return burns.',
    how: `Each E-1 runs independently on propellant from the shared tanks: the LOX downcomer and the RP-1 tank outlets feed manifolds that branch to all seven turbopumps. Pitch and yaw come from gimballing the engines together; roll comes from tilting the six outer engines sideways around the ring, all in the same rotational direction, which a single engine on the axis cannot do. Because the lips are close, the engines swing in coordinated patterns (all the same way, or all around the ring together), which move the seven exits as one group so they never close on each other. For the return, the centre engine and two opposite outer engines relight for the boostback and entry burns, and the centre engine alone performs the landing burn.`,
    why: `A cluster of mid-sized engines is easier to develop, test and build in quantity than one giant engine, and the same core also powers the upper stage. It also gives a range of thrust that one engine cannot: all seven at full power for liftoff, three for the return burns, and one throttled engine (${F.landingThrustMin} at its ${F.e1MinThrottle} minimum) for landing a booster that weighs only about ${F.boosterDryWeight} when empty (${F.boosterEmptyMass} with its legs). Seven engines at their minimum setting would still produce far too much thrust to land.`,
    phases: [
      at('leo', 'ignition', 'All seven engines start and are checked while the hold-downs keep the vehicle on the pad.'),
      at('leo', 'maxq', 'The cluster throttles down to limit aerodynamic loads, then back up.'),
      at('leo', 'meco', 'All seven shut down with a reserve kept for the booster\'s return.'),
      at('leo', 'boostback', 'The centre engine and two opposite outer engines relight to send the booster back toward the coast.'),
      at('leo', 'landing-burn', 'Only the centre engine fires for the landing.'),
      at('gto', 'meco', 'Without recovery the cluster burns almost all of its propellant before cutoff.'),
      at('station', 'maxq', `Past max-q it burns almost to depletion: the heavy crew stack leaves no propellant for a return, and near the end all seven throttle back together to hold the crew near ${F.crewGLimit}.`),
    ],
    environment: `The base region sees the harshest mix in the vehicle: radiant heat from seven sooty kerosene plumes, hot gas drawn back toward the base as the plumes widen at altitude, liftoff noise reflected from the pad, and the ambient pressure falling from about 101 kPa at sea level to nearly zero. On the return, the booster flies engines-first into the airflow, so the cluster takes the entry heating.`,
    figures: [
      { label: 'Engines', value: `${F.engines} × E-1`, note: 'One centre engine plus a ring of six' },
      { label: 'Total thrust at sea level', value: F.s1ThrustSL, note: `${F.engines} × ${F.e1ThrustSL}` },
      { label: 'Total thrust in vacuum', value: F.s1ThrustVac },
      { label: 'Total propellant flow', value: F.s1Mdot, note: 'Computed from vacuum thrust and Isp at full throttle' },
      { label: 'Burn time if every kilogram were used at full thrust', value: F.s1FullThrustBurn, note: `${F.s1Prop} ÷ ${F.s1Mdot}. Real cutoff comes earlier on recovery flights.` },
      { label: 'Liftoff thrust-to-weight ratio', value: F.liftoffTWLeo, note: `LEO configuration, ${F.liftoffMassLeo} fully fuelled (computed from the dataset)` },
    ],
    materials: mats('s1-engine-cluster'),
    materialsWhy: 'The cluster is an assembly rather than one component, so it has no material of its own in the materials table. Its materials are those of the E-1 engines (a copper-alloy chamber liner, nickel superalloys in the hot turbomachinery, stainless-steel tubes and lines) and of the thrust structure that carries them (welded aluminium alloy 2219 with titanium engine fittings). Open those parts to see why each was chosen.',
    manufacturing: 'Each engine is built, then fired on a test stand for acceptance before it is installed. On the stage the engines are mounted to the thrust structure, their thrust axes aligned by measurement, the feed lines and pressurant lines joined with sealed flanges, and the whole system leak checked with helium. A full stage with all seven engines is then usually fired while held down on a test stand.',
    inspection: 'Alignment of every thrust axis, helium leak checks of each joint, and a review of every engine\'s start, run and shutdown data. After a recovered flight, engines are inspected with borescopes (small cameras) through the nozzle and chamber, and any engine outside its limits is replaced.',
    misconception: 'Many people assume all seven engines fire whenever the booster is firing. Only the ascent uses all seven. The return burns use three engines and the landing uses one, because thrust must match what the task needs: too much thrust for a nearly empty booster makes a controlled landing impossible.',
    ifAbsent: `With one big engine of the same total thrust instead of a cluster, landing the empty booster would need that engine to run steadily at about ${F.singleEngineHoverThrottle} of full thrust (computed), far below what a large turbopump-fed engine can do, and roll control would need separate thrusters. With one of the seven E-1s out at liftoff, the thrust-to-weight ratio would fall from ${F.liftoffTWLeo} to about ${F.sixEngineTW} (LEO configuration, computed), barely enough to climb, so an engine failure just after liftoff is a demanding case.`,
    depth: {
      quick: `Seven identical engines at the bottom of the booster push together at liftoff. Having several smaller engines lets the booster turn some off later: three for flying back, one for landing.`,
      engineering: `Liftoff thrust is ${F.s1ThrustSL} against a weight of ${F.liftoffWeightLeo}, so the initial net acceleration is only about ${F.liftoffAccel}. As ${F.s1Mdot} of propellant leaves, the vehicle lightens and accelerates faster. Steering uses the engines' gimbals (${F.e1Gimbal}): tilting all seven by ${F.e1GimbalDeg} gives about ${F.sideForceCluster} of side force. An engine exit swings about ${F.gimbalExitSwing} at full gimbal, more than the ${F.nozzleLipGap} gap between neighbouring lips, so two neighbours tilted toward each other could touch; coordinated patterns never do that.`,
      materials: 'The cluster brings together three material families that each solve a different problem: a conductive copper alloy where combustion heat must pass into the coolant, nickel superalloys where metal must stay strong in hot gas, and stainless steel for tough, weldable lines at cryogenic and moderate temperatures. The thrust structure that carries the seven engines is welded aluminium with titanium fittings at the concentrated engine loads.',
    },
    demo: 'tvc',
    sources: ['nasa-grc-liquid', 'sutton-rpe', 'huzel-huang-sp125', 'nasa-bsf-14', 'nasa-srp'],
  }),

  lesson({
    id: 'engine',
    summary: `The E-1 is the booster's liquid-propellant rocket engine: it pumps liquid oxygen and RP-1 kerosene into a chamber, burns them at ${F.e1Pc} and expands the hot gas through a bell nozzle to produce ${F.e1ThrustSL} at sea level.`,
    where: `Seven E-1s hang below the first stage. Each is about ${F.e1Length} long overall, with its gimbal ${F.st.s1Gimbal} above the nozzle exit: the gimbal block and LOX dome at the top, the turbopump and gas generator beside the chamber, the bell nozzle (${F.e1Exit} across at the exit) at the bottom, and the dark turbine exhaust duct ending beside the bell.`,
    connections: ['s1-engine-cluster', 'turbopump', 'gas-generator', 'injector', 'combustion-chamber', 'nozzle', 'main-valves', 'tvc-actuators', 'igniter', 'thrust-structure'],
    function: 'Turn the chemical energy of LOX and RP-1 into a fast, directed exhaust jet. The reaction to throwing that mass backward is the thrust.',
    how: `The E-1 uses the gas-generator cycle. A turbopump raises both propellants to well above chamber pressure. The RP-1 first flows through channels in the nozzle and chamber walls, cooling them, then enters the injector with the LOX. They burn at about ${F.flameT} (the theoretical flame temperature for LOX and kerosene near this mixture ratio) and ${F.e1Pc}. The gas speeds up through the throat to the speed of sound and keeps accelerating in the widening bell, leaving at an effective exhaust velocity of about ${F.e1VeSL} at sea level (${F.e1VeVac} in vacuum). A small gas generator burns about ${F.ggFraction} of the propellant to drive the turbine and dumps its exhaust overboard.`,
    why: 'Liquid engines can be fired on a test stand before flight, throttled, shut down on command and restarted. The booster uses all four: each engine is acceptance-fired before it flies, throttles back through maximum dynamic pressure, cuts off cleanly before staging, and restarts to return and land. LOX and RP-1 are dense (small tanks), RP-1 is storable at room temperature, and the pair gives good performance for a first stage.',
    phases: [
      at('leo', 'ignition', 'The engines start, reach full thrust and are checked before release.'),
      at('leo', 'liftoff', 'Seven engines lift the fully fuelled vehicle.'),
      at('leo', 'boostback', 'Three E-1s restart in near vacuum.'),
      at('leo', 'entry-burn', 'Three E-1s fire into the oncoming air to slow the booster.'),
      at('leo', 'landing-burn', 'The centre E-1 throttles to set down the booster.'),
      at('suborbital', 'liftoff', `Only ${F.hopEngines} of the seven engines are needed to loft the light booster-only stack with the research capsule.`),
    ],
    environment: `Liquid oxygen at ${F.loxBoil} enters one side while gas near ${F.flameT} burns a few centimetres away. Pressures reach ${F.e1Pc} in the chamber and more at the pump outlets. The engine also endures intense vibration and noise, gimbal loads, and an ambient pressure that falls from sea level to vacuum during the burn.`,
    figures: [
      { label: 'Thrust, sea level / vacuum', value: `${F.e1ThrustSL} / ${F.e1ThrustVac}` },
      { label: 'Specific impulse, sea level / vacuum', value: `${F.e1IspSL} / ${F.e1IspVac}` },
      { label: 'Chamber pressure', value: F.e1Pc },
      { label: 'Mixture ratio (LOX : RP-1 by mass)', value: F.mr },
      { label: 'Propellant flow', value: F.e1Mdot, note: 'Computed: vacuum thrust ÷ (Isp × g0)' },
      { label: 'Expansion ratio', value: F.e1Eps, note: `Throat ${F.e1Throat}, exit ${F.e1Exit}` },
      { label: 'Dry mass', value: F.e1Mass, note: `Thrust about ${F.e1TW} times its own weight (computed)` },
    ],
    materials: mats('engine'),
    materialsWhy: 'The hottest surface with the highest heat flux, the chamber liner, is a copper alloy (GRCop class) because heat must pass through it quickly into the fuel. The turbine, gas generator and hot manifolds are nickel superalloys because they must stay strong and resist oxidation for minutes in gas near 900 K under high stress. Lines and the brazed nozzle tubes are stainless steel: tough at LOX temperature, compatible with both propellants, and easy to weld and braze.',
    manufacturing: 'Chamber liners are machined or 3D printed with their coolant channels, then closed out with a structural jacket; nozzle tubes are shaped, stacked and furnace brazed; turbopump parts are cast or forged and precisely machined and balanced. The engine is assembled, leak and proof tested, then fired on a test stand for acceptance before it goes on a stage.',
    inspection: 'Helium leak checks, X-ray or CT scans of welds and brazes, water flow tests of the injector, acceptance firing with hundreds of sensor channels, and after each recovered flight a borescope inspection of the chamber, throat and turbine.',
    misconception: `"The flame pushes against the air." Thrust comes from gas pressure on the inside of the chamber and nozzle as the engine throws exhaust backward; the air outside only gets in the way. That is why the same E-1 makes more thrust in vacuum (${F.e1ThrustVac}) than at sea level (${F.e1ThrustSL}).`,
    ifAbsent: 'Without an engine there is no propulsion at all. Without the liquid engine\'s abilities to throttle and restart, the booster could not limit loads at maximum dynamic pressure or fly back and land.',
    depth: {
      quick: 'Pumps push liquid oxygen and kerosene into a chamber where they burn. The hot gas squeezes through a narrow throat and speeds up in the bell-shaped nozzle. Throwing gas down that fast pushes the rocket up.',
      engineering: `Thrust F = ṁ·ve + (pe − pa)·Ae, where ve is the gas velocity at the exit and pe its pressure. In vacuum (pa = 0) the two terms together equal ṁ·c, with c = Isp·g0 the effective exhaust velocity: ${F.e1Mdot} × ${F.e1VeVac} = ${F.e1ThrustVac}. At sea level the ambient pressure pa (about 101 kPa) acting on the ${F.e1ExitArea} exit area subtracts about ${F.e1SeaLevelPressureTerm}. That gives about ${F.e1ThrustSLFromPressure}, the dataset's sea-level rating of ${F.e1ThrustSL}: the K-1's illustrative thrust figures are built from the same nozzle numbers, and the trajectory model uses the same formula as the air thins. The gas-generator cycle is simple and robust, but the turbine exhaust (about ${F.ggFraction} of the flow) leaves with little thrust, costing a few percent of specific impulse compared with a closed cycle.`,
      materials: 'An engine is a catalogue of material choices driven by temperature and chemistry: copper alloy where heat must flow, nickel superalloy where metal must stay strong while hot, stainless steel where toughness at cryogenic temperature and weldability matter, titanium only on the fuel side (it can ignite in high-pressure oxygen). Every part is tested before flight because a small flaw can grow fast at these pressures.',
    },
    demo: 'combustion',
    sources: ['nasa-grc-liquid', 'nasa-grc-thrust', 'sutton-rpe', 'huzel-huang-sp125'],
  }),

  lesson({
    id: 'turbopump',
    summary: `The turbopump is the E-1's heart: a turbine spinning at ${F.rpm} drives two pumps on one shaft that raise LOX and RP-1 from tank pressure to above chamber pressure.`,
    where: 'Mounted beside the combustion chamber on each engine. Look for the upright shaft housing parallel to the chamber: the LOX pump and the RP-1 pump each have a curved inlet duct rising to the stage feed lines, and the turbine wheel sits at one end with its hot-gas inlet from the gas generator and its exhaust into the duct beside the nozzle.',
    connections: ['engine', 'gas-generator', 'main-valves', 'lox-downcomer', 's1-fuel-tank', 'injector'],
    function: `Deliver about ${F.e1Lox} of LOX and ${F.e1Fuel} of RP-1 per engine at pressures high enough to push through the cooling channels and injector into a chamber at ${F.e1Pc}.`,
    how: `Hot gas from the gas generator expands through the turbine blades and spins the shaft. On the same shaft, each pump first uses an inducer (a screw-like rotor) to raise pressure gently, so the liquid does not boil into vapour bubbles (cavitation) at the low-pressure inlet. The centrifugal impeller then flings the liquid outward at high speed, and the spiral casing (volute) turns that speed into pressure. Seals between the pumps, purged with helium, keep LOX, kerosene and hot turbine gas from ever meeting.`,
    why: `Pumps let the tanks stay at low pressure while the chamber runs at high pressure. A pressure-fed engine would need tank pressure above chamber pressure, around ${F.pressureFedTank} (illustrative, including injector and line losses), instead of a few bar. Wall thickness of a pressurized cylinder grows in proportion to pressure (t = p·r / σ), so tanks at ${F.pressureFedTank} instead of about ${F.pumpFedTank} would need walls about ${F.pressureFedRatio} times thicker: far too heavy for a booster with ${F.s1LoxVolume} of LOX.`,
    phases: [
      at('leo', 'pad', 'LOX is bled through the pumps to chill them before start, so the first liquid does not flash to gas.'),
      at('leo', 'ignition', 'The turbopump spins up from rest to full speed in a few seconds.'),
      at('leo', 'maxq', 'Throttling changes turbine power and pump speed.'),
      at('gto', 'restart', 'The upper-stage turbopump must restart after a long coast.'),
    ],
    environment: `One shaft spans a temperature difference of about 800 K: LOX at ${F.loxBoil} on one side and fuel-rich turbine gas near 900 K on the other. It turns about ${F.rps}, carries megawatts of power, and must start from rest to full speed in seconds without cavitating.`,
    figures: [
      { label: 'Shaft speed', value: F.rpm, note: `${F.rps}; illustrative order of magnitude` },
      { label: 'LOX flow per engine', value: F.e1Lox, note: `Mixture ratio ${F.mr}` },
      { label: 'RP-1 flow per engine', value: F.e1Fuel },
      { label: 'Pump power', value: `about ${F.pumpPower}`, note: `Estimate: flow ÷ density × pressure rise ÷ efficiency, assuming illustrative pump pressure rises of ${F.loxPumpRise} (LOX) and ${F.fuelPumpRise} (RP-1) and ${F.pumpEfficiency} efficiency` },
    ],
    materials: mats('turbopump'),
    materialsWhy: 'The turbine wheel and blades are nickel superalloy because they run hot, in fuel-rich gas, under enormous centrifugal stress, and must resist creep (slow stretching under load at temperature). The LOX pump housing is aluminium alloy 2219, which is compatible with oxygen and tough at cryogenic temperature. Titanium is used only for the fuel impeller: it is strong for its weight, but titanium can ignite if rubbed or struck in high-pressure oxygen, so it is kept out of the LOX side.',
    manufacturing: 'Housings are cast and machined; impellers and inducers are machined from forgings on five-axis mills; turbine blades are cast or machined from superalloy. Rotating parts are dynamically balanced to tight tolerances, because at hundreds of revolutions per second a tiny imbalance becomes a large vibrating force. The assembled pump is spun and flow tested.',
    inspection: 'X-ray of castings, dimensional checks of blade tips and seal clearances, balance checks, a spin test, and in flight, accelerometers that watch bearing vibration. After a recovered flight: torque checks (does the shaft turn smoothly by hand?), borescope views of blades and seals, and bearing inspection.',
    misconception: `"Turbopumps are like slow water pumps." The E-1 shaft turns about ${F.rps} and the pump delivers power of order ${F.pumpPower} from a machine small enough to sit beside the chamber. The turbopump is the most highly stressed rotating machine on the vehicle.`,
    ifAbsent: `Without the turbopump the propellant would reach the chamber only at tank pressure, a few bar. The engine could not run at ${F.e1Pc}; to keep thrust it would need very heavy, highly pressurized tanks.`,
    depth: {
      quick: 'A small turbine, spun by hot gas, drives two pumps on the same shaft. They squeeze LOX and kerosene to high pressure so the tanks can stay thin and light.',
      engineering: `Pump power P = (ṁ / ρ) · Δp / η. For LOX: ${F.e1Lox} ÷ ${F.loxDensity} ≈ ${F.e1LoxVolumeFlow}; with an illustrative ${F.loxPumpRise} rise that is about ${F.loxPumpHydraulic} of hydraulic power before pump losses. The fuel pump needs a higher rise because the RP-1 must also push through the cooling channels. The inlet pressure from the tank (plus the liquid column under acceleration) must exceed the liquid's vapour pressure by a margin (the net positive suction head); the inducer lets the pump work with a smaller margin, and so with lighter, lower-pressure tanks.`,
      materials: 'Temperature and chemistry decide each material: superalloy where it is hot and highly stressed, aluminium where it touches LOX, titanium only where it touches kerosene. Balancing, clearances and seals matter as much as the alloys.',
    },
    demo: 'turbopump',
    closeup: 'turbopump-section',
    sources: ['sutton-rpe', 'huzel-huang-sp125', 'nasa-sp8107'],
  }),

  lesson({
    id: 'gas-generator',
    summary: 'The gas generator is a small combustor that burns a little of the engine\'s propellant, fuel-rich and relatively cool, to make the hot gas that spins the turbopump turbine.',
    where: 'Beside the turbopump on each E-1, fed by small tapped lines from both pump outlets. Its gas passes through the turbine and then leaves through the exhaust duct that ends beside the nozzle: the source of the dark, sooty jet next to each bright plume.',
    connections: ['turbopump', 'engine', 'igniter', 'main-valves', 'pressurization'],
    function: 'Supply turbine drive gas at a controlled temperature and flow, which sets the pump speed and therefore the engine\'s thrust.',
    how: `About ${F.ggFraction} of the engine's propellant (about ${F.e1GgFlow} per engine) burns with a large excess of fuel. The extra kerosene absorbs heat, so the gas stays near 900 K (illustrative for this engine) instead of the ${F.flameT} of the main chamber: cool enough for the turbine blades. After the turbine, the gas is dumped overboard. A heat-exchanger coil in the exhaust duct warms helium on its way to pressurize the tanks.`,
    why: 'The pumps need megawatts of shaft power, and burning a small side stream of the same propellants is the simplest way to get it. The turbine loop is separate from the main chamber, so the pumps do not have to push the whole flow through a preburner at extra pressure, which makes the gas-generator cycle easier to develop, start and control.',
    phases: [
      at('leo', 'ignition', 'The gas generator lights and spins up the turbopump during the start sequence.'),
      at('leo', 'maxq', 'Throttling is done mostly by reducing gas-generator flow and thus turbine power.'),
      at('leo', 'landing-burn', 'Deep throttling on the centre engine is set by the gas generator.'),
    ],
    environment: 'Fuel-rich combustion leaves soot (coking) on the turbine inlet. The generator sees a sharp thermal shock at every start, pressures of the same order as the main chamber (its gas only has to drive the turbine, then it is dumped, so it need not exceed chamber pressure), and continuous vibration from the turbopump.',
    figures: [
      { label: 'Share of engine propellant flow', value: F.ggFraction },
      { label: 'Flow per engine', value: F.e1GgFlow, note: 'Computed' },
      { label: 'Dumped by seven engines at full thrust', value: F.s1GgFlow, note: 'Computed' },
      { label: 'Gas temperature', value: 'about 900 K', note: 'Illustrative, set by turbine-blade limits' },
    ],
    materials: mats('gas-generator'),
    materialsWhy: 'The combustor and exhaust duct are nickel superalloy: they must keep their strength in hot, sooty, fuel-rich gas and survive repeated heating and cooling on every start. Fuel-rich gas is chosen partly because hot oxygen-rich gas would attack most metals.',
    manufacturing: 'The combustor body and injector are machined and welded; the exhaust duct is formed from sheet and welded, with the helium heat-exchanger coil brazed inside. Proof and leak tests follow, then the unit is fired as part of the engine\'s acceptance test.',
    inspection: 'Weld X-ray, leak checks, and after firing a borescope look at soot build-up and at the turbine inlet for erosion or cracks.',
    misconception: '"The dark smoke beside the flame means something is wrong." The dark jet is the gas generator\'s fuel-rich turbine exhaust, normal for a kerosene gas-generator engine. It is the visible cost of this cycle.',
    ifAbsent: 'Without the gas generator the turbopump has no power. The engine would need another way to drive its pumps (a different cycle) or would have to be pressure-fed.',
    depth: {
      quick: 'A little of the fuel and oxygen is burned on the side, with extra fuel to keep it cool. That gas spins the turbine, then is thrown away through a pipe beside the nozzle.',
      engineering: `The dumped flow is about ${F.ggFraction} of the total, and its low-temperature, low-pressure exhaust makes little thrust. The engine's overall specific impulse is therefore lower by up to a few percent than a closed (staged-combustion) cycle, which routes turbine gas into the main chamber but needs much higher pump pressures, a preburner and harder development.`,
      materials: 'Nickel superalloys keep strength and resist oxidation at the gas-generator temperature; choosing a fuel-rich mixture keeps the temperature within what the turbine blades tolerate.',
    },
    demo: 'turbopump',
    sources: ['sutton-rpe', 'huzel-huang-sp125'],
  }),

  lesson({
    id: 'injector',
    summary: 'The injector is the perforated plate at the top of the combustion chamber that sprays LOX and RP-1 into the chamber in carefully aimed jets so they mix, atomize and burn evenly.',
    where: 'At the top of the thrust chamber, under the dome-shaped LOX manifold. In the cutaway, look for the flat faceplate with concentric rings of small orifices, the radial and circular baffles standing up from the face, and the fuel manifold ring around its edge.',
    connections: ['combustion-chamber', 'main-valves', 'turbopump', 'igniter', 'engine'],
    function: 'Meter each propellant into the chamber at the right mixture ratio and break it into fine droplets that mix and burn completely and stably.',
    how: `The orifices are arranged in pairs so that a LOX jet and an RP-1 jet collide just below the face (an "unlike-impinging doublet": the two jets carry different propellants). The collision flattens the jets into sheets that break into droplets; the droplets evaporate and burn. The pressure drop across the orifices is chosen large enough that pressure waves in the chamber cannot easily push back into the feed lines. The baffles divide the face into compartments that break up sideways-travelling acoustic waves, which can otherwise couple with combustion and grow into destructive instability.`,
    why: 'Combustion efficiency, wall heating and stability are all set at the injector. Complete mixing at the intended ratio gives the design specific impulse; an even pattern keeps hot streaks off the chamber wall; stability keeps the engine from shaking itself apart.',
    phases: [
      at('leo', 'ignition', 'LOX leads into the chamber; the TEA-TEB slug arrives through the fuel orifices ahead of the RP-1 and ignites on contact.'),
      at('leo', 'liftoff', `The injector spreads ${F.e1Mdot} of propellant per engine across the chamber.`),
    ],
    environment: `The back of the faceplate is cooled by incoming LOX at ${F.loxBoil}; the front faces burning gas near ${F.flameT} only millimetres away. The face also carries the chamber pressure: roughly ${F.e1ChamberForce} pressing on it (${F.e1Pc} over a chamber about 1.7 times the throat diameter, an illustrative proportion).`,
    figures: [
      { label: 'Mixture ratio', value: F.mr, note: 'LOX mass per unit mass of RP-1' },
      { label: 'LOX / RP-1 flow per engine', value: `${F.e1Lox} / ${F.e1Fuel}`, note: 'Computed' },
      { label: 'Force of chamber pressure on the face', value: `about ${F.e1ChamberForce}`, note: 'Illustrative chamber diameter' },
    ],
    materials: mats('injector'),
    materialsWhy: 'The faceplate and element rings are stainless steel: tough at LOX temperature, compatible with oxygen when clean, and easy to drill, braze and weld. The baffles project into the hottest zone and are nickel superalloy, which keeps its strength there; they are also cooled by propellant flowing through them.',
    manufacturing: 'Hundreds of orifices are drilled or electro-discharge machined to precise diameters and angles, deburred and cleaned; rings and manifolds are brazed or welded. Every part in the oxygen path is cleaned to strict limits on particles and hydrocarbons, because contamination in oxygen can ignite.',
    inspection: 'Water flow tests measure each circuit\'s flow and show the spray pattern; orifices are checked optically for size and burrs; oxygen-cleanliness is verified before assembly. After firing, the face is inspected for erosion and heat marks that reveal hot streaks.',
    misconception: '"The injector is just a shower head." Its geometry decides whether the engine runs smoothly or destroys itself. Combustion instability in large engines was brought under control largely at the injector, with baffles and tuned element patterns.',
    ifAbsent: 'Propellants poured into the chamber unmixed would burn incompletely and unevenly: lower performance, hot streaks that burn through the wall, and a high risk of violent pressure oscillations.',
    depth: {
      quick: 'Hundreds of paired jets of oxygen and kerosene collide just below the injector face, shattering into a fine mist that burns evenly.',
      engineering: 'Unlike-impinging doublets mix at the element; the orifice pressure drop (a sizeable fraction of chamber pressure) decouples chamber oscillations from the feed system; radial and circumferential baffles damp tangential and radial acoustic modes. The outer ring is commonly biased toward fuel to keep a cooler layer of gas against the wall.',
      materials: 'Stainless steel for the precise, oxygen-clean faceplate; superalloy baffles where the metal meets the flame front. The manufacturing challenge is precision and cleanliness rather than exotic alloys.',
    },
    demo: 'combustion',
    closeup: 'injector-face',
    sources: ['sutton-rpe', 'nasa-sp8089', 'nasa-sp194'],
  }),

  lesson({
    id: 'combustion-chamber',
    summary: 'The combustion chamber is where the propellants burn at high pressure; its narrow throat sets the flow, and its thin copper-alloy wall survives only because kerosene flows through channels just behind the hot surface.',
    where: `Below the injector: a short cylinder, then a converging section down to the throat (${F.e1Throat} across), where the nozzle begins. In the cutaway, look for the comb of narrow coolant channels milled into the reddish copper liner, closed by the outer nickel-alloy jacket.`,
    connections: ['injector', 'nozzle', 'engine', 'turbopump', 'main-valves'],
    function: 'Contain combustion at high pressure long enough for it to finish, then accelerate the gas to the speed of sound at the throat.',
    how: `Regenerative cooling: RP-1 from the fuel pump enters a manifold low on the nozzle, flows up through the channels (against the gas flow) and only then goes to the injector. Heat from the ${F.flameT} gas crosses the liner's thin hot wall into the kerosene. This works because (1) the fuel is a large, cold heat sink flowing fast; (2) the copper alloy conducts heat very well, so the temperature drop across the wall is small; (3) the wall is thin. Heat flux peaks near the throat, where the mass flow per unit area (density times velocity) is greatest, so the channels are narrowest there and the coolant runs fastest. The heat is not wasted: the fuel carries it back into the chamber.`,
    why: `No metal survives ${F.flameT} on its own. Higher chamber pressure gives a smaller, lighter engine with better performance, but also higher heat flux, so a high-pressure engine needs an actively cooled wall.`,
    phases: [
      at('leo', 'ignition', 'Coolant must already be flowing when combustion starts.'),
      at('leo', 'maxq', 'Throttling lowers both heat flux and coolant flow together.'),
      at('leo', 'entry-burn', 'Relit engines again depend on fuel cooling as they fire into the airflow.'),
    ],
    environment: `Gas near ${F.flameT} at ${F.e1Pc} on one side and kerosene at high pressure on the other, separated by a hot wall of copper alloy only about a millimetre thick in engines of this class. Heat flux at the throat reaches tens of megawatts per square metre (order of magnitude for engines of this pressure class). The coolant side must stay cool enough that RP-1 does not break down and deposit carbon (coking).`,
    figures: [
      { label: 'Chamber pressure', value: F.e1Pc },
      { label: 'Throat diameter / area', value: `${F.e1Throat} / ${F.e1ThroatArea}` },
      { label: 'Gas temperature', value: `about ${F.flameT}`, note: 'Theoretical flame temperature, LOX/kerosene near this mixture ratio (Sutton & Biblarz)' },
      { label: 'Throat heat flux', value: '10 to 100 MW/m²', note: 'Order of magnitude for engines of this pressure class (Sutton & Biblarz)' },
    ],
    materials: mats('combustion-chamber'),
    materialsWhy: 'The liner is a copper alloy of the GRCop family, developed at NASA for this job: copper conducts heat roughly twenty times better than stainless steel (room-temperature values), and the added chromium-niobium particles keep it strong at temperature. A conductive liner is the point: it lets heat reach the coolant quickly. The nickel-superalloy jacket outside carries the pressure loads and closes the channels.',
    manufacturing: 'The liner is 3D printed (laser powder-bed fusion of GRCop) or machined from a forging, with its channels milled in; the superalloy jacket is then brazed on or built up by directed-energy deposition (older designs close the channels with electroformed nickel). The coolant circuit is proof tested and flow tested, and channels are checked for blockages.',
    inspection: 'CT scans of printed liners, pressure and leak tests of the coolant circuit, and after firing an inspection of the hot wall for blanching, cracks or bulging between channels. Copper liners slowly fatigue from repeated heating and cooling, which limits how many flights a chamber can make.',
    misconception: '"Cooling channels insulate the chamber." They do the opposite: they pull heat out of the wall as fast as it arrives. The liner is a good conductor on purpose; an insulating liner would only get hotter.',
    ifAbsent: 'Without cooling, the liner would melt within seconds at full power. An uncooled chamber would need to run at low pressure with ablative walls and accept lower performance and very limited reuse.',
    depth: {
      quick: 'Kerosene flows through tiny channels inside the chamber wall before it is burned. It soaks up the heat and keeps the metal from melting.',
      engineering: 'Steady heat flux q through the hot wall: q = k·ΔT / t. For a given q, a high conductivity k and a thin wall t keep the temperature drop ΔT small, so the gas-side surface stays far below the melting point while the coolant side stays below the coking limit of RP-1. The coolant pressure drop adds to what the fuel pump must supply.',
      materials: 'The key property is conductivity combined with strength at temperature: pure copper conducts well but softens; GRCop alloys keep most of the conductivity and add high-temperature strength and fatigue life. 3D printing lets complex channel shapes be made in one piece.',
    },
    demo: 'regen-cooling',
    closeup: 'cooling-channels',
    sources: ['nasa-ntrs-cooled-chambers', 'nasa-grcop', 'nasa-am-chamber', 'sutton-rpe', 'edwards-fuels', 'nist-cryo'],
  }),

  lesson({
    id: 'nozzle',
    summary: `The nozzle is the bell below the throat where the hot gas expands and accelerates to supersonic speed; on the E-1 its exit area is ${F.e1Eps} times the throat area, a size chosen for flight that starts at sea level.`,
    where: `From the throat down to the ${F.e1Exit} exit at the bottom of each E-1. Look for the fine pattern of brazed tubes running along the bell, the hoop bands (hatbands) that stiffen it, and the coolant inlet manifold ring low on the bell.`,
    connections: ['combustion-chamber', 'engine', 'base-heat-shield', 'turbopump'],
    function: 'Convert the hot gas\'s pressure and heat into directed velocity, and so into thrust.',
    how: `In the converging section the gas speeds up to exactly the speed of sound at the throat. Beyond the throat, the widening bell lets the supersonic gas keep expanding: pressure and temperature fall while velocity rises. The curved bell contour turns the flow nearly parallel to the axis in a shorter length than a cone. The tube wall is regeneratively cooled: RP-1 enters the inlet manifold low on the bell and flows up through the tubes to the chamber's channels.`,
    why: `A nozzle gives its best thrust when its exit pressure matches the ambient pressure. With an expansion ratio of ${F.e1Eps}, ideal flow gives an exit pressure of about ${F.e1ExitPressure} (estimate for a specific-heat ratio near 1.2): a little more than half the 101 kPa at sea level, so the jet is overexpanded at liftoff, but not so far that the flow separates from the wall (separation typically begins only when the wall pressure falls to roughly 0.25 to 0.4 of ambient). As the air thins, the same nozzle becomes underexpanded. A bigger bell would help higher up but would separate at sea level and would not fit seven engines in a ${F.diameter} base.`,
    phases: [
      at('leo', 'liftoff', 'Overexpanded at sea level: the plume shows shock diamonds and stays narrow.'),
      at('leo', 'maxq', 'As ambient pressure falls, the plume widens and thrust rises toward the vacuum value.'),
      at('leo', 'meco', 'Near cutoff the ambient pressure is almost zero and the plumes balloon outward.'),
    ],
    environment: 'Gas temperature falls along the bell as it expands, but the area is large, so the total heat load is high. Starting and stopping cause brief flow separation and side loads. The lower bell faces the plume recirculation and radiant heat of its six neighbours.',
    figures: [
      { label: 'Expansion ratio', value: F.e1Eps },
      { label: 'Exit diameter / area', value: `${F.e1Exit} / ${F.e1ExitArea}` },
      { label: 'Ideal exit pressure', value: `about ${F.e1ExitPressure}`, note: 'Isentropic estimate, specific-heat ratio 1.2; illustrative' },
      { label: 'Effective exhaust velocity, sea level / vacuum', value: `${F.e1VeSL} / ${F.e1VeVac}`, note: 'Isp × g0' },
    ],
    materials: mats('nozzle'),
    materialsWhy: 'The bell is made of stainless-steel tubes: formable into tapered shapes, brazeable into a gas-tight wall, and strong enough at the lower heat flux downstream of the throat. The manifolds and hatbands are nickel superalloy because they carry concentrated loads near hot metal.',
    manufacturing: 'Hundreds of tubes are tapered and bent to the bell contour, stacked around a mandrel, and furnace brazed into one wall; hatbands and manifolds are brazed or welded on. The finished nozzle is pressure tested and flow tested.',
    inspection: 'Proof pressure, leak checks, X-ray of braze joints, and dye-penetrant checks of welds. After firing: tube splits, erosion or dents from debris.',
    misconception: '"A bigger nozzle is always better." Only where the air is thin. At sea level an oversized bell expands the gas below ambient pressure; the flow separates from the wall, thrust drops and dangerous side loads appear. That is why the upper-stage E-1V has a much larger nozzle than the E-1.',
    ifAbsent: `If the gas left straight from the throat at the speed of sound, the same chamber would lose about ${F.noDivergingLossSL} of its thrust at sea level and ${F.noDivergingLossVac} in vacuum (ideal-flow estimate).`,
    depth: {
      quick: 'The bell makes the hot gas go faster. Faster exhaust means more push for the same amount of propellant.',
      engineering: `Thrust coefficient: F = CF·pc·At. Ideal CF rises with expansion ratio until the exit pressure falls below ambient; then the (pe − pa)·Ae term turns negative and, if pe drops too far, the flow separates. Choosing ε = ${F.e1Eps} balances sea-level and high-altitude performance and the base diameter available for seven engines.`,
      materials: 'Downstream of the throat the heat flux is lower, so brazed stainless tubes can do the job: they are the cooling passages and the structure at once. Tube walls are thin, so braze quality and inspection matter.',
    },
    demo: 'nozzle-pressure',
    sources: ['nasa-grc-nozzle', 'nasa-grc-thrust', 'sutton-rpe', 'nasa-sp8120', 'ussa-1976'],
  }),

  note({
    id: 'igniter',
    summary: 'A supply of TEA-TEB, a liquid that bursts into flame on contact with oxygen, used to light the E-1 and E-1V engines (and their gas generators) for every start.',
    function: 'At start, a small slug of TEA-TEB (triethylaluminium and triethylborane) is pushed ahead of the fuel into the chamber and gas generator. It ignites spontaneously on contact with the LOX already there, lighting the main propellants. The boron gives the brief green flash seen at each start.',
    why: 'Hypergolic ignition needs no spark or electrical igniter and works in vacuum. Each start consumes a dose, so the number of restarts is limited by the TEA-TEB carried: the booster engines need doses for the boostback, entry and landing burns, and the E-1V for each upper-stage restart.',
    materials: mats('igniter'),
    phases: [
      at('leo', 'ignition', 'The green flash of TEA-TEB at each of the seven engines.'),
      at('leo', 'ses1', 'The E-1V is lit by its own TEA-TEB supply.'),
      at('leo', 'coast', 'A second dose relights the E-1V for the circularization burn at the high point of the orbit.'),
      at('gto', 'restart', 'A second dose relights the upper stage after the parking-orbit coast.'),
      at('leo', 'boostback', 'Three booster engines relight with onboard TEA-TEB.'),
      at('leo', 'landing-burn', 'The centre engine\'s final relight.'),
    ],
    sources: ['sutton-rpe', 'huzel-huang-sp125'],
  }),

  lesson({
    id: 'vacuum-engine',
    summary: `The E-1V is the upper stage's single engine: the same core as the E-1 (injector, chamber, ${F.e1Throat} throat, turbopump and propellant flow) with a huge radiatively cooled nozzle extension, giving ${F.e1vThrust} and a specific impulse of ${F.e1vIsp} in vacuum, against the E-1's ${F.e1ThrustVac} and ${F.e1IspVac}.`,
    where: `Under the upper stage, hanging from its gimbal at ${F.st.s2Gimbal} on the thrust cone. During ascent its ${F.e1vLength} length reaches down inside the interstage, with the nozzle exit only ${F.nozzleClearance} above the booster's forward skirt.`,
    connections: ['nozzle-extension', 's2-tanks', 'interstage', 'tvc-actuators', 'avionics', 'stage-separation', 'igniter'],
    function: 'Carry the upper stage and payload from staging to orbit, and restart in space for missions that coast first (transfer orbits, lunar departure).',
    how: `The turbopump, gas generator, injector and regeneratively cooled chamber work as on the E-1. Below the regeneratively cooled section, a bolted niobium-alloy extension continues the bell to an expansion ratio of ${F.e1vEps}. Ideal flow then gives an exit pressure of only about ${F.e1vExitPressure}: the gas has converted more of its heat into velocity, so each kilogram of propellant produces more impulse. The chamber, throat and flow are the E-1's, so the same ${F.e1vMdot} or so of propellant now makes more thrust: ${F.e1vThrust} against ${F.e1ThrustVac} in vacuum, in the same proportion as the specific impulse.`,
    why: `The upper stage fires almost entirely above the atmosphere, so a large nozzle costs nothing in flow separation and gains a lot: ${F.e1vIsp} instead of the E-1's ${F.e1IspVac} in vacuum. The upper stage's mass is carried all the way to orbit, so its efficiency matters most: with the E-1's vacuum Isp the stage would lose about ${F.leoS2WithE1Loss} of ideal velocity change on the LEO mission (computed).`,
    phases: [
      at('leo', 'ses1', 'Ignition once the nozzle is clear of the interstage.'),
      at('leo', 'upper-burn', 'The long burn that builds orbital speed.'),
      at('leo', 'seco', `Cutoff at the low point of a ${F.leoInsertion} orbit, when guidance sees the target reached.`),
      at('leo', 'coast', `Restarts at the high point for a short burn (about ${F.leoCircDv}, computed) that makes the orbit circular.`),
      at('gto', 'restart', 'Restart after the coast in the parking orbit.'),
      at('lunar', 'tli', 'The restart that sends the probe toward the Moon.'),
      at('station', 'insertion', 'The burn that places the capsule below the station.'),
    ],
    environment: 'Near vacuum and cold soak between burns, long coasts with propellant floating in the tanks, and restarts that must work after tens of minutes in space. The extension glows red-orange during the burn.',
    figures: [
      { label: 'Vacuum thrust', value: F.e1vThrust },
      { label: 'Vacuum specific impulse', value: F.e1vIsp, note: `E-1: ${F.e1IspVac}` },
      { label: 'Expansion ratio', value: F.e1vEps, note: `Throat ${F.e1vThroat}, exit ${F.e1vExit}` },
      { label: 'Length', value: F.e1vLength },
      { label: 'Propellant flow', value: F.e1vMdot, note: 'Computed' },
      { label: 'Burn time for the full load at full thrust', value: F.s2FullThrustBurn, note: `${F.s2Prop} ÷ ${F.e1vMdot}` },
      { label: 'Gimbal range / minimum throttle', value: `${F.e1vGimbal} / ${F.e1vMinThrottle}` },
    ],
    materials: mats('vacuum-engine'),
    materialsWhy: 'Same logic as the E-1 for the core: GRCop copper-alloy liner for conduction into the coolant, nickel superalloy turbomachinery for strength in hot gas. The extension is niobium alloy C-103 because it is far from the throat, where heat flux is low enough to be radiated away by a thin, hot, refractory metal wall.',
    manufacturing: 'The core is built and acceptance-fired like an E-1. Because the extension cannot fire at sea level, vacuum-engine tests use a vacuum test cell or a shortened extension; the full extension is fitted and checked on the stage.',
    inspection: 'As for the E-1, plus inspection of the extension\'s silicide coating and joint, and a check that the extension clears the interstage in the separation geometry.',
    misconception: `"A vacuum nozzle would be even better at sea level because it is bigger." At sea level its ideal exit pressure (about ${F.e1vExitPressure}) would be about ${F.e1vSeaLevelRatio} times lower than the air around it; the flow would separate violently from the wall and could tear the extension. Big nozzles only pay in near vacuum.`,
    ifAbsent: 'Without a dedicated vacuum engine, the upper stage would use a sea-level nozzle and deliver noticeably less velocity change, costing payload on every mission.',
    depth: {
      quick: 'The upper-stage engine is the booster engine with a much longer nozzle. In the near-vacuum of high altitude, the longer nozzle gets more push from every kilogram of propellant.',
      engineering: `Isp rises from ${F.e1IspVac} to ${F.e1vIsp} with the larger expansion ratio. Ideal velocity change of the upper stage with the LEO payload: Δv = ${F.e1vIsp} × g0 × ln(m0/mf) ≈ ${F.leoS2}. Upper-stage thrust-to-weight is only a little above 1 at ignition (about ${F.s2IgnitionTWLeo} on the LEO mission) and below 1 with the heavy crew stack (about ${F.s2IgnitionTWStation} on the station mission); that is acceptable because the stage is already climbing fast and needs mainly horizontal speed. Sharing the E-1's core means one turbopump, injector and chamber design to qualify and build for both stages.`,
      materials: 'A thin radiatively cooled extension is far lighter than a tube-wall bell of the same area, but it only works where heating is modest and the wall can radiate freely into space.',
    },
    demo: 'nozzle-pressure',
    sources: ['sutton-rpe', 'nasa-sp8120', 'nasa-grc-rocket-eq', 'nasa-grc-thrust'],
  }),

  note({
    id: 'apogee-engine',
    summary: 'The geostationary satellite\'s own small liquid engine, fired at the high point of its orbit in several burns to raise the low point and turn the orbit into a circle over the equator.',
    function: `A storable bipropellant engine (a hypergolic pair that ignites on contact) with a radiatively cooled niobium chamber and nozzle; in this simulator ${F.apogeeThrust} of thrust at an Isp of ${F.apogeeIsp} (illustrative values, typical of such engines). Circularizing at apogee takes about ${F.circularizeDv} as an ideal, instantaneous burn, or about ${F.circularizePlaneDv} if it also removes the ${F.inclination} inclination (computed, two-body). For the ${F.gtoSatMass} satellite that means about ${F.apogeePropIdeal} of propellant and about ${F.apogeeBurnHoursIdeal} of firing, made as ${F.gtoBurnCount} burns of ${F.gtoBurnMins} centred on successive apogees.`,
    why: 'The launch vehicle leaves the satellite on a transfer orbit; the last large velocity change is made where it is cheapest, at apogee, where the satellite moves slowly, and the same burns remove the tilt of the orbit. A small engine is enough in orbit, where nothing has to be held up against gravity as at launch, and it keeps mass off a spacecraft that carries it for its whole life. With so little thrust one burn would last hours and spread its push over a wide arc of the orbit, wasting part of it, so the job is split into shorter burns centred on apogee that raise the perigee in steps.',
    materials: mats('apogee-engine'),
    phases: [at('gto', 'circularize', 'Fires at three successive apogees to raise the perigee and remove the tilt (explanatory, accelerated).')],
    sources: ['sutton-rpe', 'nasa-bsf-4'],
  }),

  lesson({
    id: 'service-module',
    summary: `The service module is the cylinder under the crew capsule that supplies power, propulsion and cooling in orbit, then is discarded before entry.`,
    where: `Below the capsule's heat shield on the capsule configuration: ${F.smDiameter} in diameter, ${F.smLength} long, with radiator panels on its skin, two solar-array wings, clusters of small thrusters, and its main engine nozzle at the bottom inside an adapter ring on the upper stage.`,
    connections: ['capsule', 'heat-shield', 'solar-arrays', 'attitude-thrusters', 'mli-blankets', 'payload-adapter'],
    function: 'Carry the propellant, main engine and thrusters for orbit changes (the burns up to the station, departure and deorbit), generate electrical power, and reject heat through radiators.',
    how: `Its main engine (${F.smThrust}, ${F.smIsp}) burns nitrogen tetroxide with monomethylhydrazine (NTO/MMH), a hypergolic pair that ignites on contact, so no igniter is needed and restarts are simple. Propellant tanks sit inside the cylinder; pressurant pushes the liquids to the engine. Radiators on the outside emit waste heat to space; the solar arrays feed batteries and the capsule.`,
    why: `Everything needed only in orbit rides in the service module so the capsule, which must carry a heat shield, stays small. Before entry the module is discarded and burns up, so its mass never has to be protected. The deorbit burn is its last job: a retrograde change of about ${F.deorbitDv} lowers the far side of the ${F.leoAlt} circular orbit to about ${F.deorbitPerigee} (two-body estimate), deep enough in the atmosphere to bring the capsule down.`,
    phases: [
      at('station', 'capsule-sep', 'Separates from the upper stage with the capsule; its arrays deploy.'),
      at('station', 'phasing', 'Powers, cools and points the capsule through the coasting laps in the lower orbit.'),
      at('station', 'raise', 'Its engine makes the two burns that raise the orbit to just below the station.'),
      at('return', 'deorbit', 'The retrograde burn that starts the return.'),
      at('return', 'sm-sep', 'Discarded before entry interface; it burns up.'),
    ],
    environment: 'Vacuum, sunlight and shadow every orbit, micrometeoroids, and the launch loads of carrying the capsule. Its propellants are toxic and must be sealed perfectly.',
    figures: [
      { label: 'Diameter / length', value: `${F.smDiameter} / ${F.smLength}` },
      { label: 'Mass', value: F.smMass },
      { label: 'Main engine thrust / Isp', value: `${F.smThrust} / ${F.smIsp}` },
      { label: 'Deorbit burn', value: `about ${F.deorbitDv}`, note: `Uses about ${F.smDeorbitProp} of propellant in about ${F.smDeorbitBurn} (computed for the ${F.smStackAtUndock} capsule and module at undocking, which still hold the ${F.smPropAtUndock} of propellant left after the climb to the station); about ${F.smPropAfterDeorbit} remains afterwards, a margin of about ${F.smMarginDv}` },
    ],
    materials: mats('service-module'),
    materialsWhy: 'Primary structure is welded aluminium alloy 2219, light and well understood. Propellant tanks are titanium: strong for their weight and compatible with the storable propellants. MLI blankets control the temperature of tanks and lines so the propellants neither freeze nor overheat.',
    manufacturing: 'Machined and welded aluminium structure; titanium tanks from formed and welded hemispheres; tubing welded and leak checked; blankets fitted by hand. The finished module goes through vibration and thermal-vacuum tests.',
    inspection: 'Helium leak checks of the propulsion system, proof tests of tanks, electrical checks, and inspection of radiator coatings.',
    misconception: '"The service module comes home with the crew." It is discarded before entry and burns up; only the capsule has a heat shield.',
    ifAbsent: 'The capsule would need its own large engine, tanks, arrays and radiators behind its heat shield: a much larger and heavier entry vehicle.',
    depth: {
      quick: 'A service module is the capsule\'s toolbox: engine, fuel, power and cooling. It is thrown away before the capsule comes home.',
      engineering: `Propellant for a burn: Δm = m0·(1 − e^(−Δv/(Isp·g0))). For the deorbit, m0 = ${F.smStackAtUndock} (capsule and module at undocking), Δv = ${F.deorbitDv}, Isp = ${F.smIsp}: about ${F.smDeorbitProp}. Hypergolic propellants trade some performance for storability over months and reliable restarts.`,
      materials: 'Aluminium where mass and simplicity rule, titanium where propellant compatibility and pressure matter, MLI where temperature must be held in vacuum.',
    },
    sources: ['sutton-rpe', 'nasa-bsf-3', 'nasa-sst-soa'],
  }),
];
