/**
 * Recovery and return lessons: the booster's grid fins, landing legs and cold-gas thrusters, the
 * capsule's parachutes and the launch abort tower.
 */
import type { PartLesson, PartNote } from '../types';
import { at, lesson, mats } from './util';
import { F } from './derived';

export const RECOVERY: (PartLesson | PartNote)[] = [
  lesson({
    id: 'grid-fins',
    summary: `Four titanium lattice fins near the top of the booster that fold out after the boostback and steer it through the atmosphere on the way down, using no propellant.`,
    where: `On the booster's forward skirt at ${F.st.gridFins}, just below the interstage, spaced 90° apart. Each is ${F.gridFinSize}, a frame filled with a lattice of thin walls; during ascent they lie folded flat against the skirt on their hinges.`,
    connections: ['s1-lox-tank', 'interstage', 'cold-gas-rcs', 'landing-legs', 's1-engine-cluster'],
    function: 'Control the booster\'s attitude and steer it toward the landing zone while it falls through the atmosphere, engines first.',
    how: `Air flows through the lattice cells; each cell wall acts as a small wing, so the fin produces a large force from a compact frame. Rotating a fin about its hinge (up to ${F.gridFinDeflection}) changes that force and turns the booster. Because the booster falls engines first, the fins are at its trailing end relative to the airflow, like the feathers of an arrow, which also makes the falling booster naturally more stable.`,
    why: 'Grid fins stay effective from high supersonic speeds down to subsonic, where flat fins of the same size would either lose effectiveness or need large, heavy actuators. Their short chord keeps the force close to the hinge line, so the actuators can be small, and they fold flat against the body for the climb.',
    phases: [
      at('leo', 'booster-coast', 'Fold out after the boostback burn.'),
      at('leo', 'entry-burn', 'Hold attitude as the booster meets denser air.'),
      at('leo', 'aero-guidance', 'Steer the booster toward the landing zone.'),
      at('suborbital', 'aero-guidance', 'Steer the booster back to the landing zone after the hop.'),
      at('station', 'aero-guidance', 'The same return on the station mission.'),
    ],
    environment: 'High dynamic pressure in the lower atmosphere, heating at high Mach after the entry burn (the booster\'s own plume also washes around it), and large aerodynamic loads on the hinges.',
    figures: [
      { label: 'Number / size', value: `${F.gridFinCount} × ${F.gridFinSize}` },
      { label: 'Maximum deflection', value: F.gridFinDeflection },
      { label: 'Hinge height', value: F.st.gridFins, note: 'Near the top of the booster' },
    ],
    materials: mats('grid-fins'),
    materialsWhy: 'Titanium keeps its strength at the temperatures reached after the entry burn, so the fins need no ablative coating and can be reused many times. Documented aluminium grid fins needed a coating and still charred. Titanium\'s strength per kilogram suits a structure far from the centre of mass, where every kilogram also shifts the balance.',
    manufacturing: 'Each fin is a single piece: cast and machined (or machined from a forging), so there are no joints in the lattice. Hinges and actuator fittings are machined and bolted on.',
    inspection: 'X-ray or CT scans for casting flaws, dye-penetrant checks for surface cracks, and post-flight inspection of hinge fittings and heat marks.',
    misconception: '"Grid fins are air brakes." They add some drag, but their job is steering. Most of the slowing down comes from the entry and landing burns and the drag of the whole booster.',
    ifAbsent: 'Without aerodynamic steering, the booster would fall where its ballistic arc takes it and would need more propellant (and a larger reserve) to correct its path with the engines.',
    depth: {
      quick: 'The waffle-like fins at the top of the booster fold out on the way down and tilt to steer it, like the feathers on an arrow.',
      engineering: 'Lattice fins have many short chords in parallel: high lift per unit span, low hinge moment, good effectiveness at high Mach. Near Mach 1 the cells can choke (the flow cannot pass through), reducing effectiveness, so the guidance allows for it. Drag is higher than a flat fin of the same span.',
      materials: 'Titanium avoids the mass and refurbishment of ablative coatings. One-piece construction avoids fatigue at welded joints in a heavily loaded lattice.',
    },
    demo: 'booster-recovery',
    closeup: 'grid-fin-lattice',
    sources: ['grid-fins-aiaa', 'nasa-grc-stability'],
  }),

  lesson({
    id: 'landing-legs',
    summary: `Four carbon-fibre legs folded against the booster's lower body that swing open seconds before touchdown to give it a wide, stable stance on the landing pad.`,
    where: `Along the aft section, hinged at ${F.legHinge} and lying flush against the body during the climb (${F.legLength} long when stowed). Deployed, the feet stand on a circle about ${F.legFootprint} in radius. Look for the telescoping deploy strut on each leg and the foot pad at its tip.`,
    connections: ['thrust-structure', 's1-fuel-tank', 'grid-fins', 's1-engine-cluster'],
    function: 'Support the booster upright on the pad, absorb the last of its vertical speed at touchdown, and resist tipping over.',
    how: 'Pressurized gas drives the telescoping struts to swing the legs down and lock them. At touchdown, crushable aluminium honeycomb in the foot pads (and the struts) deforms, turning the remaining kinetic energy into heat by permanently crushing. The wide footprint puts the booster\'s centre of mass well inside the base, so it does not tip.',
    why: `Every kilogram of leg rides the whole ascent and must also be decelerated and landed. The legs weigh ${F.legMass} (${F.legsFractionOfDry} of the booster's dry mass), so they must be light and stow flush to add little drag. In the ideal rocket-equation estimate for this vehicle, each 100 kg added to the booster costs about ${F.tradeS1} of LEO payload; the propellant reserve kept for the return costs far more.`,
    phases: [
      at('leo', 'landing-burn', 'Deploy seconds before touchdown and take the landing load.'),
      at('suborbital', 'landing-burn', 'Deploy for the landing after the suborbital hop.'),
      at('station', 'landing-burn', 'The same landing on the station mission.'),
    ],
    environment: 'Stowed in the airflow during the climb and the return, deployed into air moving at tens of metres per second, heated by the landing plume near the engines, then hit by the touchdown load. The landing zone is by the sea, so salt spray matters for reuse.',
    figures: [
      { label: 'Number', value: F.legCount },
      { label: 'Stowed length', value: F.legLength },
      { label: 'Footprint radius', value: F.legFootprint },
      { label: 'Mass of the set', value: F.legMass, note: `${F.legsFractionOfDry} of booster dry mass (illustrative dataset)` },
    ],
    materials: mats('landing-legs'),
    materialsWhy: 'Leg struts are carbon-fibre sandwich: very stiff and strong for their mass, which is what a long, lightly built strut needs. The foot pads use crushable aluminium honeycomb, which absorbs energy at a nearly constant force as its cells fold: a controlled, one-time crumple zone.',
    manufacturing: 'Composite struts laid up on mandrels and cured; metal fittings bonded and bolted at the ends; honeycomb crush cores cut to size and fitted in replaceable cartridges.',
    inspection: 'Ultrasonic scans of the composite for delamination after each landing, replacement of crushed cores, and deployment tests of the struts.',
    misconception: '"The legs cushion a hard landing like springs." The engine does almost all of the braking. The legs only absorb the last few metres per second, and the crushable cores do it once, then are replaced.',
    ifAbsent: 'The booster would have to land on its engine bells, which would be damaged and could not keep it upright; or it would need to be caught by ground equipment.',
    depth: {
      quick: 'Four light legs fold out just before landing and the booster stands on them. A crushable pad in each foot soaks up the final bump.',
      engineering: 'Tip-over stability: the resultant of weight and any lateral load must pass inside the footprint. Energy to absorb is ½·m·v² at touchdown; with a crush force roughly constant, the stroke needed scales with the square of the touchdown speed, which is why the landing burn must null the velocity precisely.',
      materials: 'Composite struts for stiffness per kilogram, sacrificial metal honeycomb for predictable energy absorption.',
    },
    demo: 'booster-recovery',
    sources: ['nasa-bsf-14', 'nasa-grc-rocket-eq', 'nasa-ceus'],
  }),

  lesson({
    id: 'cold-gas-rcs',
    summary: 'Nitrogen cold-gas thrusters at the top of the booster that turn it around after separation and hold its attitude when the engines are off and the air is too thin for the fins.',
    where: 'In pods on the booster\'s forward skirt near the grid fins, at the top of the booster: the farthest point from the centre of mass, so each small puff has the most leverage. Nitrogen bottles (COPVs) and valves sit inside the skirt.',
    connections: ['grid-fins', 'pressurization', 's1-lox-tank', 'interstage'],
    function: 'Rotate the booster (the flip after separation), aim it for the boostback and entry burns, damp rotations, and push propellant toward the tank outlets before a relight.',
    how: 'High-pressure nitrogen is released through fast valves into small nozzles. There is no combustion: the gas simply expands and accelerates, so the thrust is small but instantly available, any number of times. Firing thrusters on opposite sides in opposite directions rotates the booster without pushing it sideways.',
    why: 'Right after separation the booster is above most of the atmosphere, its engines are off and its fins are folded, so thrust vector control and aerodynamics are both unavailable. Only reaction thrusters can turn it.',
    phases: [
      at('leo', 'flip', 'Turn the booster around so its engines face the direction of travel.'),
      at('leo', 'booster-coast', 'Hold attitude over the top of the arc.'),
      at('leo', 'entry-burn', 'Aim the booster before the entry burn.'),
      at('suborbital', 'booster-coast', 'Flip the booster after the capsule separates.'),
    ],
    environment: 'Near vacuum at the start of the return, then thickening air; cold nitrogen expansion; launch vibration while stowed.',
    figures: [
      { label: 'Specific impulse (nitrogen cold gas)', value: 'about 70 s', note: `Typical for nitrogen (Sutton & Biblarz); compare ${F.e1IspVac} for the E-1 in vacuum` },
    ],
    materials: mats('cold-gas-rcs'),
    materialsWhy: 'Valves and lines are titanium: strong and light for high-pressure gas service. The nitrogen is stored in carbon-fibre overwrapped pressure vessels, which hold high pressure for a fraction of the mass of an all-metal bottle.',
    manufacturing: 'Machined valve bodies and small nozzles, welded titanium tubing, filament-wound bottles; the system is proof and leak tested as an assembly.',
    inspection: 'Leak checks, valve response tests, and thruster firing checks before flight; bottle cycle records for fatigue life.',
    misconception: '"The white puffs are small rocket engines burning fuel." They are cold nitrogen. The gas cools as it expands, and the puff is visible because it is dense, cold gas lit by the Sun (and may condense moisture near the ground).',
    ifAbsent: 'The booster could not flip for the boostback in near vacuum, and it would tumble on its way into the atmosphere.',
    depth: {
      quick: 'Small jets of compressed nitrogen at the top of the booster turn it around in space, where fins do not work.',
      engineering: 'Torque = thrust × lever arm; placing the thrusters at the top of a long booster maximizes the arm. Cold gas has low Isp, but for rotations (not large velocity changes) that matters little, and simplicity, cleanliness and unlimited restarts matter more.',
      materials: 'Titanium and carbon-overwrapped bottles: the high-pressure gas system is sized by pressure and mass, not heat.',
    },
    demo: 'booster-recovery',
    sources: ['sutton-rpe', 'nasa-copv'],
  }),

  lesson({
    id: 'parachutes',
    summary: `Two drogue parachutes and three large main parachutes that slow the capsule from high subsonic speed to a gentle splashdown.`,
    where: `Packed tightly in bags in the capsule's forward bay, around the top of the pressure vessel. Deployed, the ${F.drogues} drogues (${F.drogueDiameter} across) stream above the capsule, then the ${F.mains} mains (${F.mainDiameter} across) open on long risers.`,
    connections: ['capsule', 'backshell-tps', 'heat-shield', 'docking-system'],
    function: 'Stabilize the capsule and slow it in stages to a splashdown speed its structure and crew can take.',
    how: `The drogues are fired out by mortars at high altitude (several kilometres) and slow and steady the capsule. At lower altitude they are released and pilot chutes pull out the mains. The mains open first reefed: a line around the canopy's skirt holds it partly closed. After a few seconds cutters sever the reefing line and the canopies open fully (disreef).`,
    why: `Opening force is proportional to the canopy's drag area times the dynamic pressure at that moment. Reefing keeps the area small while the capsule is still fast, and only opens fully once it has slowed: two moderate jolts instead of one violent one. Three mains are sized so that two can still bring the capsule down at a survivable speed (estimated ${F.descentTwo} on two versus ${F.descentThree} on three), a documented practice for crewed capsules.`,
    phases: [
      at('return', 'drogues', 'Mortar-deployed drogues slow and stabilize the capsule.'),
      at('return', 'mains', 'Mains open reefed, then fully.'),
      at('return', 'splashdown', 'Steady descent to the water under three canopies.'),
      at('suborbital', 'parachutes', 'The same sequence after the suborbital hop.'),
    ],
    environment: 'Packed for weeks in a cold, vacuum environment, then deployed into high-speed air with violent opening loads; salt water at splashdown.',
    figures: [
      { label: 'Drogues / mains', value: `${F.drogues} × ${F.drogueDiameter} / ${F.mains} × ${F.mainDiameter}` },
      { label: 'Area of one main canopy', value: F.mainArea, note: 'Nominal disk area' },
      { label: 'Descent speed on three / two mains', value: `${F.descentThree} / ${F.descentTwo}`, note: `Estimate at sea level: ${F.capsuleMass}, drag coefficient 0.8 on nominal area` },
      { label: 'Falling speed with no parachutes', value: `about ${F.noChuteSpeed}`, note: 'Estimate at sea level, drag coefficient 1.3 on the base area' },
    ],
    materials: mats('parachutes'),
    materialsWhy: 'Canopies are nylon: light, strong, and elastic enough to absorb opening shock by stretching. Risers and reefing lines are aramid fibre, much stronger for their weight and heat resistant, where loads concentrate and where a line must be cut cleanly by a pyrotechnic cutter.',
    manufacturing: 'Gores are cut and sewn with reinforcing tapes; each seam and line is inspected. Packing is done by hand, then the pack is pressed to high density so it fits the bag. The whole system is qualified by drop tests.',
    inspection: 'Stitch-by-stitch inspection, documented packing steps, and inspection of recovered parachutes for tears and burns.',
    misconception: '"Parachutes should open fully as fast as possible." A full canopy opened at high speed would jerk the capsule so hard it could break lines or injure the crew. Reefing opens them in stages on purpose.',
    ifAbsent: `The capsule would hit the sea at about ${F.noChuteSpeed} (estimate): not survivable.`,
    depth: {
      quick: 'Small parachutes slow the capsule first, then three huge ones open in two steps so the jolt stays gentle.',
      engineering: 'Descent speed v = √(2·m·g / (ρ·Cd·A)): halving the area raises the speed by √2. Opening load ≈ Cd·A(t)·½ρv², so limiting A while v is high (reefing) caps the peak force. Clusters open slightly unevenly; designs allow for that.',
      materials: 'Textiles are the lightest way to create hundreds of square metres of drag: nylon for canopies that stretch, aramid for the high-load lines.',
    },
    demo: 'capsule-return',
    sources: ['knacke-parachutes', 'nasa-sp8066', 'ussa-1976'],
  }),

  lesson({
    id: 'launch-abort-system',
    summary: `The abort tower on top of the capsule carries a powerful solid rocket motor that can pull the crew away from a failing launch vehicle, and is thrown away once it is no longer needed.`,
    where: `On the capsule's apex, ${F.towerLength} long: a truss attaching to the capsule, the abort motor with four canted nozzles near its base, a jettison motor above, and a nose section with small canards.`,
    connections: ['capsule', 'docking-system', 'parachutes', 'service-module'],
    function: 'In an emergency on the pad or during the early climb, lift the capsule away from the launch vehicle fast and far enough for the parachutes to work; otherwise, jettison itself when the climb is past the dense atmosphere.',
    how: `On an abort signal the capsule separates from the service module and the abort motor fires: ${F.towerThrust} for a few seconds, about ${F.lesTW} times the weight of the capsule plus tower (computed). The nozzles are canted so the exhaust misses the capsule. Canards then turn the capsule heat shield first, the tower is jettisoned and the parachutes open. On a normal flight only the jettison motor fires, after staging.`,
    why: `A launch vehicle failure can happen faster than any crew could react, and on the pad the capsule has no height or speed to work with; only a large, instantly available solid motor can get it clear. After staging the danger is lower and the service module's engine can handle aborts, so the ${F.towerMass} tower is dropped: carried to orbit it would cost the upper stage about ${F.towerCarriedLoss} of ideal velocity change (computed).`,
    phases: [
      at('station', 'pad', 'Armed while the crew boards and the vehicle is fuelled.'),
      at('station', 'maxq', 'The most demanding abort case: highest aerodynamic loads.'),
      at('station', 'abort-jettison', 'Jettison motor pulls the tower away after staging.'),
    ],
    environment: 'Must work in the worst case: from rest on the pad, or at maximum dynamic pressure, with a failing vehicle underneath. Its own plume and the acceleration of an abort are severe; on a normal flight it sees ordinary launch loads until jettison.',
    figures: [
      { label: 'Length / mass', value: `${F.towerLength} / ${F.towerMass}` },
      { label: 'Abort motor thrust', value: F.towerThrust },
      { label: 'Thrust-to-weight in an abort', value: `about ${F.lesTW}`, note: `With the ${F.capsuleMass} capsule, computed` },
    ],
    materials: mats('launch-abort-system'),
    materialsWhy: 'The tower fairing and nose are carbon-fibre sandwich, stiff and light for an aerodynamic shell. The abort motor nozzles are nickel superalloy to survive a short, very hot solid-propellant exhaust.',
    manufacturing: 'Solid motors are cast (propellant poured into the case and cured), then inspected and stored; the truss and fairing are built and fitted like other composite and metal structures.',
    inspection: 'X-ray or CT of the solid propellant grain for cracks and voids, which would change how it burns; functional tests of the abort sequence; pad-abort and in-flight abort tests for a new design.',
    misconception: '"The tower helps lift the rocket, or is a lightning rod." It is a rescue system. On a normal flight its abort motor never fires; only the jettison motor does, to throw it away.',
    ifAbsent: 'Without an abort system, a failure on the pad or during the early climb would leave the crew with no escape.',
    depth: {
      quick: 'The tower is an emergency escape rocket. If the launch vehicle fails, it pulls the capsule to safety; if all goes well, it is thrown away after staging.',
      engineering: 'Design cases: pad abort (reach enough height and downrange distance for the parachutes to open, clear of the fireball) and maximum-dynamic-pressure abort (highest aerodynamic loads and fastest separation needed). Canted nozzles avoid plume impingement; canards give the capsule a reliable heat-shield-forward attitude.',
      materials: 'Composite for the shell, superalloy for nozzles that must survive seconds of intense heat; the motor itself is a cast solid-propellant grain.',
    },
    sources: ['nasa-les-apollo', 'sutton-rpe', 'nasa-grc-rocket-eq'],
  }),
];
