/**
 * Structures lessons: intertank, thrust structure, raceway, interstage, common bulkhead and the
 * payload fairing.
 */
import type { PartLesson, PartNote } from '../types';
import { at, lesson, mats, note } from './util';
import { F } from './derived';

export const STRUCTURES: (PartLesson | PartNote)[] = [
  lesson({
    id: 's1-intertank',
    summary: 'The intertank is the unpressurized ring of structure that joins the booster\'s fuel tank to its LOX tank and carries every load between them.',
    where: `Between the RP-1 tank's forward dome and the LOX tank's aft dome, about ${F.intertankLength} long between the dome equators. Look for the stringer-stiffened skin (closely spaced lengthwise ribs) and ring frames; the downcomer passes through its middle, and vent and access openings are cut into it.`,
    connections: ['s1-fuel-tank', 's1-lox-tank', 'lox-downcomer', 'raceway', 'pressurization'],
    function: 'Transfer thrust, weight and bending between the two tanks, and house the domes, the downcomer and the lines that pass between them.',
    how: 'Unlike the tank barrels, the intertank has no internal pressure to stiffen it, so it relies on its own geometry: lengthwise stringers resist buckling under compression, ring frames keep the section round, and the skin carries shear. Loads enter and leave through the heavy rings where the tank walls attach.',
    why: 'Two separate tanks with their own domes are simpler to build, test and inspect than a shared bulkhead, and they leave room for the downcomer and for the domes to bulge without touching. The intertank is the price: a few metres of extra structure and length.',
    phases: [
      at('leo', 'maxq', 'Peak bending with no pressure stabilization.'),
      at('leo', 'meco', 'Highest acceleration: the heavy LOX tank above presses down hardest.'),
      at('leo', 'entry-burn', 'Carries reversed loads as the booster decelerates engines-first.'),
    ],
    environment: `Cold from the LOX dome above and near ambient from the fuel dome below, so the structure has temperature gradients. Axial compression from the LOX tank, the upper stage and the payload accelerating above it, bending near maximum dynamic pressure, and on the return the loads of deceleration.`,
    figures: [
      { label: 'Length between dome equators', value: F.intertankLength, note: 'Computed from the stations' },
      { label: 'Diameter', value: F.diameter },
      { label: 'Dome height (each)', value: F.domeHeight, note: 'Ellipsoidal domes, R/√2' },
    ],
    materials: mats('s1-intertank'),
    materialsWhy: 'Skin-stringer panels are aluminium-lithium, whose high stiffness per kilogram helps against buckling, the governing failure in an unpressurized shell. Ring frames are aluminium 2219, easy to form and weld.',
    manufacturing: 'Skin panels with integrally machined or riveted stringers are curved to shape and joined to machined ring frames with fasteners; the intertank is bolted or welded to the tank rings at each end.',
    inspection: 'Fastener and joint inspection, dimensional checks of roundness (buckling is sensitive to imperfections), and a structural test article loaded to failure to validate the design.',
    misconception: '"The intertank is an empty spacer." It carries all the load between the tanks, and because it cannot use internal pressure for stiffness it is designed very differently from the tanks it connects.',
    ifAbsent: 'Without it, the tanks would have to share a common bulkhead, as the upper stage does: shorter and lighter, but harder to build and inspect, with no room for the downcomer\'s entry.',
    depth: {
      quick: 'The intertank is the short section between the two tanks. It is not pressurized, so it uses stiffening ribs to carry the weight and push of everything above.',
      engineering: 'Unpressurized cylinders under axial compression fail by buckling at loads well below the material\'s strength, and are very sensitive to small imperfections; designers apply empirical knockdown factors. Stringers and frames raise the buckling load; stiffness (Young\'s modulus) per unit density is the key material property.',
      materials: 'Aluminium-lithium for stiffness per kilogram in the skins, 2219 for frames. The design case is stability, not strength.',
    },
    sources: ['nasa-sp8007', 'nasa-isogrid', 'nasa-al-li-crush'],
  }),

  lesson({
    id: 'thrust-structure',
    summary: `The thrust structure gathers the push of seven engines, up to ${F.s1ThrustVac} in vacuum, from seven small mounting points and spreads it evenly into the cylindrical wall of the booster.`,
    where: 'In the thrust section at the base of the booster, between the base heat shield (1.3 m) and the fuel tank\'s aft dome (4.3 m). In the cutaway: radial beams and a thrust ring meeting at the engine mounts, the gimbal points at 2.3 m, the four hold-down fittings and the landing-leg hinges on the aft skirt.',
    connections: ['s1-engine-cluster', 'engine', 's1-fuel-tank', 'tvc-actuators', 'base-heat-shield', 'landing-legs', 'launch-mount'],
    function: 'Carry engine thrust into the vehicle, carry the vehicle\'s weight on the pad through the hold-downs, anchor the gimbal actuators, and carry landing loads through the legs.',
    how: 'Each engine\'s gimbal block bolts to a titanium mount fitting; beams run from the mounts to a thrust ring and the aft skirt, which spread the concentrated loads around the circumference so the thin tank wall above receives a nearly uniform push. The engines push; the whole vehicle above is pushed from below, so everything above the thrust structure is in compression.',
    why: 'Engine thrust arrives at seven points, but the tank wall can only accept load spread around its whole circumference. Without a structure to distribute it, each engine would punch into the dome.',
    phases: [
      at('leo', 'ignition', 'The load path reverses: the hold-downs pull down while the engines push up.'),
      at('leo', 'liftoff', `Carries ${F.s1ThrustSL} into the vehicle.`),
      at('leo', 'meco', 'Peak thrust-to-mass ratio of the burn.'),
      at('leo', 'landing-burn', 'Centre-engine thrust and then the leg loads at touchdown.'),
    ],
    environment: `The highest concentrated loads in the vehicle; vibration and noise at liftoff; heat from the engine bay (the base heat shield protects it); on the pad, the hold-downs restrain about ${F.holdDownNet} net upward load when all engines are at full thrust (LEO configuration, computed).`,
    figures: [
      { label: 'Thrust carried at liftoff', value: F.s1ThrustSL },
      { label: 'Thrust in vacuum at full throttle', value: F.s1ThrustVac },
      { label: 'Net hold-down load before release', value: F.holdDownNet, note: 'Thrust minus weight, LEO configuration, computed' },
      { label: 'Side force at full gimbal', value: F.sideForceCluster, note: `Seven engines at 5°, computed` },
    ],
    materials: mats('thrust-structure'),
    materialsWhy: 'The frame is aluminium 2219, machined and welded: light, well characterised and easy to join. The engine mount fittings are titanium, which is strong and stiff for its weight, resists fatigue under the vibrating engine loads, and tolerates the warmer environment near the engines.',
    manufacturing: 'Beams and fittings machined from forgings and plate; the frame welded and bolted together; fittings installed with precisely drilled, reamed holes so that engine alignment is repeatable.',
    inspection: 'Weld and fastener inspection, dimensional checks of the engine mount pattern, and a structural qualification test to beyond flight loads. On reused boosters: crack inspection (dye penetrant, eddy current) at the fittings.',
    misconception: '"The engines lift the rocket by pulling it." A rocket is pushed from the base. Everything above the thrust structure is squeezed lengthwise, which is why thin tanks need pressure and stiffeners to avoid buckling.',
    ifAbsent: 'The engines would have no stiff, strong mounting; thrust would be concentrated at seven points on a thin dome, and the gimbal actuators would have nothing to push against.',
    depth: {
      quick: 'The engines push up on a strong frame at the bottom of the booster, which spreads the push around the rocket\'s wall.',
      engineering: 'Load path: gimbal block, mount fitting, radial beams, thrust ring, aft skirt, fuel-tank barrel. The structure must also be stiff: flexibility under engine loads would shift thrust directions and interact with the steering loop.',
      materials: 'Titanium where loads concentrate and fatigue matters, aluminium where large welded structure must stay light.',
    },
    sources: ['sutton-rpe', 'nasa-std-5001', 'nasa-bsf-14'],
  }),

  note({
    id: 'raceway',
    summary: 'The external raceway is the long conduit on the side of the booster that carries electrical cables and pressurant lines between the forward and aft ends.',
    function: 'Routes power, data and some high-pressure lines past the tanks without penetrating them, under a formed aluminium cover that protects them from the airflow and heating.',
    why: 'Running cables through the tanks would mean many sealed penetrations through cryogenic, pressurized walls. An external conduit is simpler to build and inspect, at the cost of a small bump on the outer shape.',
    materials: mats('raceway'),
    phases: [
      at('leo', 'maxq', 'Its cover takes aerodynamic pressure and heating.'),
      at('leo', 'entry-burn', 'Protects cabling during the booster\'s hot return.'),
    ],
    sources: ['nasa-bsf-14'],
  }),

  lesson({
    id: 'interstage',
    summary: `The interstage is the dark carbon-composite shell between the booster and the upper stage; it houses the upper-stage engine's long nozzle and carries the separation system at its top.`,
    where: `On top of the booster, from 37.9 m to the separation plane at 44.4 m (${F.interstageLength} long). Inside, the E-1V nozzle extension hangs down ${F.nozzleInsideInterstage} below the separation plane, its exit only ${F.nozzleClearance} above the forward skirt. The pneumatic pushers and release collets ring its upper edge.`,
    connections: ['stage-separation', 'vacuum-engine', 'nozzle-extension', 's1-lox-tank', 's2-tanks', 'grid-fins'],
    function: 'Carry all loads from the upper stage and payload into the booster, give the vehicle a smooth outer shape over the upper-stage engine, and hold the separation hardware.',
    how: 'A sandwich wall (carbon-fibre face sheets bonded to an aluminium honeycomb core) makes a stiff, light cylinder. Metal rings at each end transfer loads into the booster and the separation joint. It stays with the booster when the stages separate.',
    why: 'The upper-stage engine needs its long vacuum nozzle, which must be protected during ascent and must slide out cleanly at separation. A light, stiff composite shell does both with little mass.',
    phases: [
      at('leo', 'maxq', 'Carries the bending and compression of the upper stack.'),
      at('leo', 'staging', 'The upper stage slides out of it; the E-1V nozzle must clear before ignition.'),
      at('leo', 'aero-guidance', 'Returns with the booster as its top section.'),
    ],
    environment: 'Compression and bending from the upper stack, aerodynamic pressure and heating on the outside, and at separation the dynamic loads of release. On recovery flights it flies through entry heating and the return.',
    figures: [
      { label: 'Length', value: F.interstageLength, note: 'From the forward skirt top to the separation plane' },
      { label: 'Upper-stage nozzle inside it', value: F.nozzleInsideInterstage },
      { label: 'Clearance below the nozzle exit', value: F.nozzleClearance },
    ],
    materials: mats('interstage'),
    materialsWhy: 'Carbon-fibre face sheets on an aluminium honeycomb core give very high bending stiffness per kilogram: the face sheets carry tension and compression far from the middle of the wall, the light core holds them apart and carries shear. The dark colour is the bare composite.',
    manufacturing: 'Face-sheet plies are laid on a large cylindrical mould (by hand or automated fibre placement), the honeycomb core bonded between them, and the assembly cured under heat and pressure. Metal end rings are bonded and bolted in.',
    inspection: 'Ultrasonic scanning and thermography look for disbonds between skin and core and for delaminations, which are invisible from the outside. Tap testing checks small areas. Recovered interstages are rescanned.',
    misconception: '"The interstage belongs to the upper stage." In this vehicle it stays with the booster and returns with it.',
    ifAbsent: 'The upper stage would need a short nozzle to avoid a gap between stages, losing specific impulse, or the booster and upper stage would have no structural connection sized for the long nozzle.',
    depth: {
      quick: 'The black section between the stages hides the upper-stage engine\'s long nozzle. It is a light carbon-fibre sandwich and stays with the booster.',
      engineering: `At separation the upper stage must move ${F.nozzleInsideInterstage} relative to the booster before its nozzle is clear. At a push-off speed of the order of 1 m/s that takes several seconds, which is why the E-1V ignites a few seconds after separation.`,
      materials: 'Sandwich construction trades inspection difficulty (hidden disbonds) for stiffness per kilogram. Anisotropy lets designers place fibres where the loads run.',
    },
    demo: 'sandwich-panel',
    closeup: 'separation-joint',
    sources: ['nasa-ceus', 'sutton-rpe'],
  }),

  lesson({
    id: 'common-bulkhead',
    summary: 'The common bulkhead is the single curved wall inside the upper stage that separates the LOX above from the RP-1 below: an insulated sandwich that replaces two domes and an intertank.',
    where: 'Inside the upper stage at 49.9 m (its rim) bulging down to about 48.6 m into the RP-1. In the cutaway, look for the dome drawn as two thin metal skins with a core between them.',
    connections: ['s2-tanks', 'vacuum-engine', 'pressurization'],
    function: 'Keep the two propellants apart, hold the pressure difference between the tanks in either direction, and limit heat flow from the fuel into the LOX.',
    how: 'Two aluminium 2219 dome skins are bonded to an insulating honeycomb core. The LOX pressure plus the weight of the LOX column pushes down on the dome, which bulges toward the fuel: a dome pressed on its concave side is in tension, which it carries well. If the fuel side pressure ever exceeded the LOX side, the dome would be loaded on its convex side and could buckle, so pressures are controlled to keep the difference in the safe direction (or the dome is designed for reversal).',
    why: 'Upper-stage mass costs payload almost kilogram for kilogram, and a shorter stage is lighter and stiffer. One shared dome saves a dome, an intertank and roughly a dome height of length.',
    phases: [
      at('leo', 'upper-burn', 'Holds the pressure difference as both tanks drain.'),
      at('gto', 'parking-coast', 'Limits heat flow into the LOX during the long coast.'),
      at('leo', 'pad', 'LOX loading chills one side while RP-1 stays warm on the other.'),
    ],
    environment: `LOX at ${F.loxBoil} on one side and RP-1 at near ambient on the other: a steep temperature difference across a few centimetres. Pressure difference in normal flight in one direction, with the risk of reversal during transients; the weight of the LOX under acceleration.`,
    figures: [
      { label: 'Rim / apex height', value: '49.9 m / 48.6 m', note: 'Dome bulges down into the fuel tank' },
      { label: 'Dome height', value: F.domeHeight },
      { label: 'Payload cost of upper-stage mass', value: `about ${F.tradeS2} per 100 kg`, note: 'Ideal rocket-equation estimate, LEO mission' },
    ],
    materials: mats('common-bulkhead'),
    materialsWhy: 'The skins are aluminium 2219 because it welds well into the tank structure and stays tough at LOX temperature. The core is a honeycomb chosen for low thermal conductivity: it slows heat flow so the RP-1 near the bulkhead does not get too cold and thick (and the LOX does not boil), while holding the skins apart to make a stiff sandwich.',
    manufacturing: 'Skins are formed to dome shape and bonded to the core under heat and pressure; the edge ring is welded into the tank barrels. The core cavity is sealed and vented so a leak in either skin can be detected.',
    inspection: 'Ultrasound and thermography for disbonds; leak checking of the core cavity (a leak in either skin lets propellant into the core); proof pressure tests in both directions. Documented upper stages with common bulkheads have found this the hardest part to build and inspect.',
    misconception: '"A common bulkhead is just a thin wall between two liquids." It is a load-carrying pressure dome, a thermal insulator and a sandwich structure at once, and it must be safe for pressure from either side.',
    ifAbsent: 'The upper stage would need two domes and an intertank like the booster: longer and heavier, costing payload almost one-for-one.',
    depth: {
      quick: 'One shared, insulated dome separates the upper stage\'s oxygen and fuel. It saves the weight and length of a second dome.',
      engineering: 'Net load on the bulkhead: Δp = (p_LOX + ρ_LOX·a·h) − p_RP1. With the dome convex toward the fuel, positive Δp puts the skins in membrane tension; negative Δp puts them in compression, where thin domes buckle at low loads. The sandwich core adds bending stiffness and thermal resistance.',
      materials: 'A metal-core-metal sandwich solves a structural and a thermal problem at once. Documented designs used fibreglass-phenolic honeycomb for this insulating role.',
    },
    demo: 'sandwich-panel',
    sources: ['saturn-v-flight-manual', 'nasa-ceus', 'nasa-sp8007'],
  }),

  lesson({
    id: 'fairing',
    summary: `The fairing is the ${F.fairingDiameter} nose shell that protects the satellite from air pressure, heating and noise during the climb through the atmosphere, then splits in two and falls away.`,
    where: `On top of the upper stage, from the payload interface at 53.9 m to the tip at 67.0 m (${F.fairingLength} long): a short boat-tail widening from the stage diameter, a cylinder, and an ogive nose. The seam between its two halves runs up the sides; hinges sit at its base and pushers along the seam.`,
    connections: ['payload-adapter', 'satellite-bus', 'avionics', 's2-tanks', 'service-tower'],
    function: 'Shield the payload during atmospheric flight, give the vehicle an aerodynamic nose, keep the payload clean on the pad, and then separate cleanly once the air is thin.',
    how: `Each half is a sandwich: ${F.fairingFace} carbon-fibre face sheets on a ${F.fairingCore} aluminium honeycomb core. The core holds the skins apart so the wall is stiff against the pressure of the airflow and damps some of the noise. Vents let the inside pressure follow the falling outside pressure. At separation, latches along the seam and around the base release, pneumatic pushers open the halves, which rotate outward on their base hinges and then fly free.`,
    why: `Once the vehicle is above most of the atmosphere, the fairing is ${F.fairingMass} of dead weight. It is released as early as the heating on the exposed payload allows (after upper-stage ignition in this profile). Carrying it all the way to orbit would cost the upper stage about ${F.leoS2CarryingFairingLoss} of ideal velocity change on the LEO mission (computed).`,
    phases: [
      at('leo', 'pad', 'Conditioned, filtered air flows into it through an umbilical.'),
      at('leo', 'maxq', 'Carries the peak aerodynamic pressure and nose heating.'),
      at('leo', 'fairing', 'Splits and falls away once the air is thin.'),
      at('gto', 'fairing', 'Released in the same way on the transfer mission.'),
      at('lunar', 'fairing', 'Released before the probe is exposed to space.'),
    ],
    environment: 'Liftoff noise reflected from the pad and the roar of transonic flight, the peak dynamic pressure, aerodynamic heating at the nose, and a rapidly falling outside pressure. Inside, the payload must stay clean and within its temperature limits.',
    figures: [
      { label: 'Diameter / length', value: `${F.fairingDiameter} / ${F.fairingLength}` },
      { label: 'Face sheet / core thickness', value: `${F.fairingFace} / ${F.fairingCore}` },
      { label: 'Mass', value: F.fairingMass },
      { label: 'Bending stiffness gain from the core', value: `about ${F.sandwichStiffnessRatio} ×`, note: 'Sandwich versus the two face sheets bonded into one solid laminate of the same fibre mass (geometry only, computed)' },
    ],
    materials: mats('fairing'),
    materialsWhy: 'Carbon-fibre face sheets are stiff and strong for their weight and can be laid in the directions the loads run. The aluminium honeycomb core is mostly air: it adds little mass but carries the shear between the skins and multiplies the wall\'s bending stiffness. Together they make a large, light shell that does not flex much under air pressure or ring loudly under acoustic loads.',
    manufacturing: 'Each half is laid up on a large mould, the core bonded between the face sheets, and cured under heat and pressure (in an autoclave or out of it). Separation rails, hinges, vents and access doors are then fitted; many documented fairings add acoustic blankets inside.',
    inspection: 'Ultrasonic and thermographic scans for disbonds and voids; separation tests of complete fairings in a vacuum chamber for new designs; fit checks with the payload envelope.',
    misconception: '"The fairing protects the payload from the vacuum of space." Satellites are built for vacuum. The fairing protects against the atmosphere: air pressure, heating, wind and noise. It is vented so the pressure inside follows the pressure outside, and it is thrown away as soon as the air is thin enough.',
    ifAbsent: 'A satellite with folded arrays and antennas would face the full airflow at maximum dynamic pressure and be torn apart, or it would itself have to be streamlined and much stronger (heavier).',
    depth: {
      quick: 'The nose cone is a light shell that shields the satellite from air, heat and noise. When the rocket is high enough, it splits in two and falls away.',
      engineering: `Bending stiffness of a sandwich per unit width ≈ E·tf·d²/2 (d = distance between face-sheet centres) versus E·h³/12 for a solid laminate of thickness h = 2·tf. With tf = ${F.fairingFace} and a ${F.fairingCore} core, the ratio is about ${F.sandwichStiffnessRatio}. Release timing balances free-molecular heating of the exposed payload against the mass carried.`,
      materials: 'Face sheets carry the loads, the core holds them apart: a sandwich is the most mass-efficient way to make a large stiff panel, but its bond lines are hidden and must be inspected by ultrasound or thermography.',
    },
    demo: 'fairing-sep',
    closeup: 'fairing-sandwich',
    sources: ['nasa-ceus', 'nasa-grc-dynpress', 'nasa-bsf-14'],
  }),
];
