/** Core references identified for this build (see ACCURACY.md for how each was used). */
import type { Source } from '../types';

export const CORE_SOURCES: Source[] = [
  { id: 'nasa-grc-liquid', title: 'Liquid Rocket Engine', publisher: 'NASA Glenn Research Center, Beginner’s Guide to Aeronautics', url: 'https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/liquid-rocket-engine/', used: 'Liquid engine operation, propellant feed, thrust', accessed: 'reference' },
  { id: 'nasa-grc-rocket-eq', title: 'Ideal Rocket Equation', publisher: 'NASA Glenn Research Center, Beginner’s Guide to Aeronautics', url: 'https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/ideal-rocket-equation/', used: 'Ideal rocket equation and its assumptions', accessed: 'reference' },
  { id: 'nasa-grc-thrust', title: 'Rocket Thrust Equation', publisher: 'NASA Glenn Research Center, Beginner’s Guide to Aeronautics', url: 'https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/rocket-thrust-equation/', used: 'Thrust with pressure term', accessed: 'reference' },
  { id: 'nasa-bsf-3', title: 'Basics of Space Flight, Chapter 3: Gravity and Mechanics (orbits, coasting)', publisher: 'NASA Science', url: 'https://science.nasa.gov/learn/basics-of-space-flight/chapter3-4/', used: 'Orbital mechanics, coasting, Kepler', accessed: 'reference' },
  { id: 'nasa-bsf-4', title: 'Basics of Space Flight, Chapter 4: Trajectories', publisher: 'NASA Science', url: 'https://science.nasa.gov/learn/basics-of-space-flight/chapter4-1/', used: 'Transfer orbits, gravity assists, trajectories', accessed: 'reference' },
  { id: 'nasa-bsf-14', title: 'Basics of Space Flight, Chapter 14: Launch', publisher: 'NASA Science', url: 'https://science.nasa.gov/learn/basics-of-space-flight/chapter14-1/', used: 'Launch sequence and operations', accessed: 'reference' },
  { id: 'nasa-ntrs-rendezvous', title: 'Reference frames and rendezvous/capture equations (NTRS 19930020463)', publisher: 'NASA Technical Reports Server', url: 'https://ntrs.nasa.gov/citations/19930020463', used: 'Relative motion (Clohessy-Wiltshire) for rendezvous', accessed: 'reference' },
  { id: 'nasa-ntrs-cooled-chambers', title: 'Fluid-cooled combustion chambers (NASA SP-8087 series, NTRS 19730022965)', publisher: 'NASA Technical Reports Server', url: 'https://ntrs.nasa.gov/api/citations/19730022965/downloads/19730022965.pdf', used: 'Regenerative cooling representation', accessed: 'reference' },
  { id: 'nasa-grcop', title: 'GRCop and bimetallic cooled combustion chambers (NTRS 20190033311)', publisher: 'NASA Technical Reports Server', url: 'https://ntrs.nasa.gov/citations/20190033311/', used: 'Copper-alloy chamber liners (GRCop-42/84)', accessed: 'reference' },
  { id: 'nasa-am-chamber', title: 'NASA and Virgin Orbit 3D print test rocket combustion chamber', publisher: 'NASA', url: 'https://www.nasa.gov/technology/nasa-and-virgin-orbit-3d-print-test-rocket-combustion-chamber/', used: 'Additive manufacturing of copper-alloy chambers', accessed: 'reference' },
  { id: 'nasa-al-li-crush', title: 'NASA engineers crush fuel tank to build better rockets', publisher: 'NASA', url: 'https://www.nasa.gov/technology/nasa-engineers-crush-fuel-tank-to-build-better-rockets/', used: 'Aluminium-lithium tank buckling test', accessed: 'reference' },
  { id: 'nasa-ceus', title: 'Composites for Exploration Upper Stage (CEUS)', publisher: 'NASA Space Technology Mission Directorate', url: 'https://www.nasa.gov/space-technology-mission-directorate/tdm/composites-for-exploration-upper-stage-ceus/', used: 'Composite upper-stage structures', accessed: 'reference' },
  { id: 'nasa-ablators', title: 'Thermal Protection Materials Branch: Low Density Ablators', publisher: 'NASA Ames Research Center', url: 'https://www.nasa.gov/general/thermal-protection-materials-branch-low-density-ablators/', used: 'Ablative heat shields (PICA, Avcoat class)', accessed: 'reference' },
  { id: 'nasa-reusable-tps', title: 'Thermal Protection Materials Branch: Reusable Materials', publisher: 'NASA Ames Research Center', url: 'https://www.nasa.gov/general/thermal-protection-materials-branch-reusable-materials/', used: 'Reusable ceramic tiles and insulation', accessed: 'reference' },
  { id: 'nasa-3d-resources', title: 'NASA 3D Resources (textures and usage guidance)', publisher: 'NASA', url: 'https://science.nasa.gov/3d-resources/', used: 'Tycho star map texture; usage guidance', accessed: 'read' },
  { id: 'nasa-blue-marble', title: 'Blue Marble: Next Generation', publisher: 'NASA Earth Observatory / Visible Earth', url: 'https://visibleearth.nasa.gov/collection/1484/planet-textures', used: 'Earth day imagery', accessed: 'reference' },
  { id: 'threejs-color', title: 'Color management', publisher: 'three.js manual', url: 'https://threejs.org/manual/pages/color-management.html', used: 'Colour spaces of textures and output', accessed: 'reference' },
  { id: 'aisc-360', title: 'AISC 360: Specification for Structural Steel Buildings', publisher: 'American Institute of Steel Construction', url: 'https://www.aisc.org/publications/steel-standards/', used: 'Structural steel design practice for towers and frames', accessed: 'reference' },
  { id: 'nasa-ksc-refractory', title: 'Refractory materials for launch-pad flame deflectors (NASA Kennedy Space Center corrosion and materials research)', publisher: 'NASA Technical Reports Server (search)', url: 'https://ntrs.nasa.gov/search?q=refractory%20concrete%20flame%20trench', used: 'Refractory concrete and flame trench protection', accessed: 'reference' },
  { id: 'nasa-ksc-sound-suppression', title: 'Launch pad sound suppression water systems (NASA Kennedy Space Center)', publisher: 'NASA Technical Reports Server (search)', url: 'https://ntrs.nasa.gov/search?q=sound%20suppression%20water%20launch%20pad', used: 'Water deluge for acoustic suppression', accessed: 'reference' },
];
