import type { Source } from '../types';

/**
 * Sources cited by the part lessons and phase cards (owned by the parts content), in addition
 * to the core list in core.ts. None of these was opened during this build (no access to the
 * publishers' sites from the build environment), so every entry is `accessed: 'reference'`:
 * identified by title, used for principles the text states qualitatively or with a stated
 * condition. Where the exact document number was uncertain, the URL is a search of the NASA
 * Technical Reports Server for the title rather than a guessed document link.
 */
export const PART_SOURCES: Source[] = [
  {
    id: 'sutton-rpe',
    title: 'Rocket Propulsion Elements, 9th edition (G. P. Sutton and O. Biblarz, 2017)',
    publisher: 'John Wiley & Sons',
    url: 'https://www.wiley.com/en-us/Rocket+Propulsion+Elements%2C+9th+Edition-p-9781118753651',
    used: 'Engine cycles, turbopumps, injectors, chamber cooling, nozzle expansion and flow separation, thrust vector control, cold-gas and monopropellant thrusters, flame temperatures',
    accessed: 'reference',
  },
  {
    id: 'huzel-huang-sp125',
    title: 'Design of Liquid Propellant Rocket Engines, NASA SP-125, 2nd edition (D. K. Huzel and D. H. Huang, 1971); revised as Modern Engineering for Design of Liquid-Propellant Rocket Engines (AIAA, 1992)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/citations/19710019929',
    used: 'Gas-generator cycle, turbopump and valve design, start and shutdown sequencing, tank pressurization, feed systems',
    accessed: 'reference',
  },
  {
    id: 'nasa-sp194',
    title: 'Liquid Propellant Rocket Combustion Instability, NASA SP-194 (D. T. Harrje and F. H. Reardon, editors, 1972)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/citations/19720026079',
    used: 'Injector baffles, acoustic combustion instability and how injector pressure drop decouples the feed system',
    accessed: 'reference',
  },
  {
    id: 'nasa-sp8089',
    title: 'Liquid Rocket Engine Injectors, NASA SP-8089 (Space Vehicle Design Criteria, 1976)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Liquid%20rocket%20engine%20injectors%22',
    used: 'Impinging injector elements, face cooling, flow calibration',
    accessed: 'reference',
  },
  {
    id: 'nasa-sp8107',
    title: 'Turbopump Systems for Liquid Rocket Engines, NASA SP-8107 (Space Vehicle Design Criteria, 1974)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Turbopump%20systems%20for%20liquid%20rocket%20engines%22',
    used: 'Inducers and cavitation, turbine drive, shaft seals between propellants, balancing',
    accessed: 'reference',
  },
  {
    id: 'nasa-sp8120',
    title: 'Liquid Rocket Engine Nozzles, NASA SP-8120 (Space Vehicle Design Criteria, 1976)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Liquid%20rocket%20engine%20nozzles%22',
    used: 'Bell contours, tube-wall nozzles, radiatively cooled extensions, flow separation and side loads',
    accessed: 'reference',
  },
  {
    id: 'nasa-valves',
    title: 'Liquid Rocket Valve Assemblies (NASA Space Vehicle Design Criteria monograph, 1973)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Liquid%20rocket%20valve%20assemblies%22',
    used: 'Main propellant valve types, actuation and sealing at cryogenic temperature',
    accessed: 'reference',
  },
  {
    id: 'nasa-pogo',
    title: 'Prevention of Coupled Structure-Propulsion Instability (POGO), NASA SP-8055 (Space Vehicle Design Criteria, 1970)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Prevention%20of%20coupled%20structure-propulsion%20instability%22',
    used: 'Feed-line and structure coupling (pogo) and accumulators in LOX lines',
    accessed: 'reference',
  },
  {
    id: 'nasa-sp8007',
    title: 'Buckling of Thin-Walled Circular Cylinders, NASA SP-8007 (revised 2020)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Buckling%20of%20thin-walled%20circular%20cylinders%22',
    used: 'Axial-compression buckling of thin shells and the stabilizing effect of internal pressure',
    accessed: 'reference',
  },
  {
    id: 'nasa-isogrid',
    title: 'Isogrid Design Handbook, NASA CR-124075 (1973)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Isogrid%20design%20handbook%22',
    used: 'Grid-stiffened (isogrid and orthogrid) shells machined from plate',
    accessed: 'reference',
  },
  {
    id: 'saturn-v-flight-manual',
    title: 'Saturn V Flight Manual, SA-503 (MSFC-MAN-503, 1968)',
    publisher: 'NASA Marshall Space Flight Center (via NASA Technical Reports Server)',
    url: 'https://ntrs.nasa.gov/search?q=%22Saturn%20V%20flight%20manual%22',
    used: 'Documented designs: a kerosene first stage with the LOX tank forward and suction lines through the fuel tank, helium bottles inside the LOX tank, fuel used as gimbal hydraulic fluid, helium injection against LOX geysering, and an insulated common bulkhead on an upper stage',
    accessed: 'reference',
  },
  {
    id: 'nasa-copv',
    title: 'Composite Overwrapped Pressure Vessels, A Primer (NASA/SP-2011-573)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Composite%20overwrapped%20pressure%20vessels%22%20primer',
    used: 'COPV construction (liner plus fibre overwrap), autofrettage, proof testing, damage tolerance and stress rupture',
    accessed: 'reference',
  },
  {
    id: 'nasa-std-5001',
    title: 'NASA-STD-5001, Structural Design and Test Factors of Safety for Spaceflight Hardware',
    publisher: 'NASA Technical Standards System',
    url: 'https://standards.nasa.gov/standard/NASA/NASA-STD-5001',
    used: 'Proof testing and design factors for pressurized structures',
    accessed: 'reference',
  },
  {
    id: 'nist-cryo',
    title: 'Material Properties (cryogenic thermal contraction and conductivity data)',
    publisher: 'NIST Cryogenic Technologies Group',
    url: 'https://trc.nist.gov/cryogenics/materials/materialproperties.htm',
    used: 'Thermal contraction of aluminium alloys between room temperature and LOX temperature; conductivity of copper and stainless steel',
    accessed: 'reference',
  },
  {
    id: 'edwards-fuels',
    title: 'Liquid Fuels and Propellants for Aerospace Propulsion: 1903-2003 (T. Edwards, Journal of Propulsion and Power 19(6), 2003)',
    publisher: 'AIAA',
    url: 'https://doi.org/10.2514/2.6942',
    used: 'RP-1 refinement, thermal stability and coking in cooling channels',
    accessed: 'reference',
  },
  {
    id: 'ussa-1976',
    title: 'U.S. Standard Atmosphere, 1976 (NOAA, NASA, USAF; NASA-TM-X-74335)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/citations/19770009539',
    used: 'Sea-level pressure and density; how air density falls with altitude (dynamic pressure, nozzle ambient pressure, parachute descent)',
    accessed: 'reference',
  },
  {
    id: 'nasa-grc-stability',
    title: 'Rocket Stability (Beginner’s Guide to Rockets)',
    publisher: 'NASA Glenn Research Center',
    url: 'https://www.grc.nasa.gov/www/k-12/rocket/rktstab.html',
    used: 'Centre of mass versus centre of pressure',
    accessed: 'reference',
  },
  {
    id: 'nasa-grc-dynpress',
    title: 'Dynamic Pressure (Beginner’s Guide to Aeronautics)',
    publisher: 'NASA Glenn Research Center',
    url: 'https://www.grc.nasa.gov/www/k-12/airplane/dynpress.html',
    used: 'Definition of dynamic pressure, q = 0.5 ρ v²',
    accessed: 'reference',
  },
  {
    id: 'nasa-grc-nozzle',
    title: 'Nozzle Design (Beginner’s Guide to Aeronautics)',
    publisher: 'NASA Glenn Research Center',
    url: 'https://www.grc.nasa.gov/www/k-12/airplane/nozzled.html',
    used: 'Converging-diverging nozzle flow, choking at the throat, exit pressure',
    accessed: 'reference',
  },
  {
    id: 'grid-fins-aiaa',
    title: 'Grid Fins: A New Concept for Missile Stability and Control (W. D. Washington and M. S. Miller, AIAA Paper 93-0035, 1993)',
    publisher: 'AIAA',
    url: 'https://arc.aiaa.org/doi/10.2514/6.1993-35',
    used: 'Grid (lattice) fin aerodynamics: effectiveness at high Mach, low hinge moments, transonic choking',
    accessed: 'reference',
  },
  {
    id: 'nasa-srp',
    title: 'Supersonic retropropulsion research for entry, descent and landing (NASA technical reports)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22supersonic%20retropropulsion%22',
    used: 'Engines fired into a supersonic oncoming flow: plume and shock interaction, heating and drag',
    accessed: 'reference',
  },
  {
    id: 'allen-eggers',
    title: 'A Study of the Motion and Aerodynamic Heating of Ballistic Missiles Entering the Earth’s Atmosphere at High Supersonic Speeds (H. J. Allen and A. J. Eggers, NACA Report 1381, 1958)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22NACA%20Report%201381%22',
    used: 'Why blunt bodies: a detached shock carries most entry energy away as hot air',
    accessed: 'reference',
  },
  {
    id: 'knacke-parachutes',
    title: 'Parachute Recovery Systems Design Manual, NWC TP 6575 (T. W. Knacke, 1991)',
    publisher: 'Defense Technical Information Center',
    url: 'https://apps.dtic.mil/sti/citations/ADA247666',
    used: 'Reefing and opening shock, canopy drag coefficients, clusters, deployment by mortar and pilot chute',
    accessed: 'reference',
  },
  {
    id: 'nasa-sp8066',
    title: 'Deployable Aerodynamic Deceleration Systems, NASA SP-8066 (Space Vehicle Design Criteria, 1971)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Deployable%20aerodynamic%20deceleration%20systems%22',
    used: 'Drogue and main parachute staging, reefing',
    accessed: 'reference',
  },
  {
    id: 'nasa-les-apollo',
    title: 'Apollo Experience Report: Launch Escape Propulsion Subsystem (NASA Technical Note)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Apollo%20experience%20report%22%20%22launch%20escape%20propulsion%20subsystem%22',
    used: 'Tower abort motors with canted nozzles, jettison motors, abort cases',
    accessed: 'reference',
  },
  {
    id: 'idss',
    title: 'International Docking System Standard (IDSS) Interface Definition Document',
    publisher: 'International Space Station partner agencies',
    url: 'https://www.internationaldockingstandard.com/',
    used: 'Soft capture and hard capture, androgynous docking interface, sealing',
    accessed: 'reference',
  },
  {
    id: 'nasa-sst-soa',
    title: 'State-of-the-Art of Small Spacecraft Technology',
    publisher: 'NASA Ames Research Center, Small Spacecraft Systems Virtual Institute',
    url: 'https://www.nasa.gov/smallsat-institute/sst-soa/',
    used: 'Spacecraft subsystems: solar cells and arrays, reaction wheels and star trackers, monopropellant thrusters, thermal control, radio links',
    accessed: 'reference',
  },
  {
    id: 'nasa-mli',
    title: 'Multilayer Insulation Material Guidelines, NASA/TP-1999-209263 (M. M. Finckenor and D. Dooling)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22Multilayer%20insulation%20material%20guidelines%22',
    used: 'MLI layers, spacers, venting, grounding and outer-layer materials',
    accessed: 'reference',
  },
  {
    id: 'kopp-lean-tsi',
    title: 'A new, lower value of total solar irradiance: Evidence and climate significance (G. Kopp and J. L. Lean, Geophysical Research Letters 38, 2011)',
    publisher: 'American Geophysical Union',
    url: 'https://doi.org/10.1029/2010GL045777',
    used: 'Sunlight intensity above the atmosphere, about 1,361 W/m²',
    accessed: 'reference',
  },
  {
    id: 'nasa-sound-suppression',
    title: 'Launch pad sound suppression and water deluge systems (NASA technical reports)',
    publisher: 'NASA Technical Reports Server',
    url: 'https://ntrs.nasa.gov/search?q=%22sound%20suppression%22%20launch%20pad%20water',
    used: 'Water injection to reduce liftoff acoustic loads and protect the pad',
    accessed: 'reference',
  },
];
