"""Build the KIMBLE / ONE / FAB identity artwork (original vector design).

The symbol: a custom K. Its stem is the vehicle on the pad; its upper arm is an ascent arc
that leaves the stem steeply and pitches over until it runs horizontal at the tip (the
gravity turn: orbit needs sideways speed); the leg is the stable stance below. Wordmarks are
glyph outlines from Archivo (SIL OFL 1.1), tracked and set by this script.

Writes public/brand/*.svg and src/brand/logoPaths.ts (path data used to paint decals).
"""
import json, subprocess, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
GRAPHITE = '#16181c'
ACCENT = '#6a5af9'
WHITE = '#ffffff'

# ── the K symbol, in a 100 x 100 box ──────────────────────────────────────────
STEM = 'M10 6 H27 V94 H10 Z'
# ascent arc: outer edge rises from the stem and turns horizontal at the tip
ARM = ('M27 55 '
       'C30.5 37 45 11.5 94 7 '   # outer (upper) edge, ending horizontal
       'L94 23 '                   # blunt tip, 16 units thick
       'C57 26.5 44 42 40.5 57 '   # inner (lower) edge sweeping back down
       'L27 68 Z')
LEG = 'M40.5 49 L94 94 H72.5 L33 60.5 Z'
MARK_D = f'{STEM} {ARM} {LEG}'


def glyphs(text, wght, wdth, track):
    out = subprocess.check_output(['python3', str(ROOT / 'tools/brand/glyphs.py'), text, str(wght), str(wdth), str(track)], cwd=ROOT)
    return json.loads(out)


word = glyphs('KIMBLE', 720, 125, 0.075)
onefab = glyphs('ONE / FAB', 600, 112, 0.2)
sub = glyphs('ROCKET ENGINEERING', 560, 112, 0.22)

CAP = word['capHeight']  # font units


def word_group(g, height, x, y, fill):
    """Place a glyph run so its cap height is `height` units, baseline at y."""
    s = height / g['capHeight']
    return f'<path transform="translate({x:.3f} {y:.3f}) scale({s:.6f})" d="{g["d"]}" fill="{fill}"/>', g['width'] * s


def svg(w, h, body, title):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:.2f} {h:.2f}" role="img" aria-label="{title}">'
            f'<title>{title}</title>{body}</svg>\n')


def mark(fill, arm_fill=None, x=0, y=0, s=1.0):
    af = arm_fill or fill
    return (f'<g transform="translate({x} {y}) scale({s})">'
            f'<path d="{STEM} {LEG}" fill="{fill}"/><path d="{ARM}" fill="{af}"/></g>')


out = ROOT / 'public/brand'
out.mkdir(parents=True, exist_ok=True)

# symbol only
for name, fill, arm in [('kimble-mark', GRAPHITE, None), ('kimble-mark-light', WHITE, None), ('kimble-mark-accent', GRAPHITE, ACCENT)]:
    (out / f'{name}.svg').write_text(svg(100, 100, mark(fill, arm), 'KIMBLE'))

# horizontal lockup: mark + KIMBLE wordmark (cap height 58 % of the mark)
def lockup(fill, arm=None, with_sub=False):
    wg, ww = word_group(word, 50, 124, 75, fill)
    body = mark(fill, arm) + wg
    width = 124 + ww
    height = 100
    if with_sub:
        sg, sw = word_group(sub, 12, 126, 97, fill)
        body += sg
        width = max(width, 126 + sw)
    return svg(width + 2, height, body, 'KIMBLE')

(out / 'kimble-logo.svg').write_text(lockup(GRAPHITE))
(out / 'kimble-logo-dark.svg').write_text(lockup(GRAPHITE))
(out / 'kimble-logo-light.svg').write_text(lockup(WHITE))
(out / 'kimble-logo-accent.svg').write_text(lockup(GRAPHITE, ACCENT))

# ONE / FAB secondary wordmark
og, ow = word_group(onefab, 40, 0, 44, GRAPHITE)
(out / 'one-fab.svg').write_text(svg(ow, 48, og, 'ONE / FAB'))
og2, _ = word_group(onefab, 40, 0, 44, WHITE)
(out / 'one-fab-light.svg').write_text(svg(ow, 48, og2, 'ONE / FAB'))

# path data for the runtime decal painter
def scaled(g, height):
    return {'d': g['d'], 'scale': height / g['capHeight'], 'width': g['width'] * height / g['capHeight'], 'capHeight': height}

ts = ROOT / 'src/brand/logoPaths.ts'
ts.parent.mkdir(parents=True, exist_ok=True)
ts.write_text(
    '/* Generated by tools/brand/build_logo.py. Do not edit by hand. */\n'
    '/** KIMBLE symbol paths in a 100 x 100 box (stem+leg, and the ascent arm). */\n'
    f'export const MARK = {{ body: {json.dumps(STEM + " " + LEG)}, arm: {json.dumps(ARM)}, size: 100 }};\n'
    '/** Glyph runs: path in font units (y down, baseline 0); scale converts to a cap height of 1 unit * capHeight. */\n'
    f'export const WORD_KIMBLE = {json.dumps(scaled(word, 1))};\n'
    f'export const WORD_ONEFAB = {json.dumps(scaled(onefab, 1))};\n'
    f'export const WORD_SUB = {json.dumps(scaled(sub, 1))};\n'
)
print('ok', ow, word['width'])
